import { Inject, Injectable, Logger } from '@nestjs/common';
import {
  AgentRole,
  type FunctionalRequirement,
  type IntentAnalysis,
  type NonFunctionalRequirement,
  type RequirementDocument,
} from '@archivato/shared';
import { BaseAgent } from '../agent.base';
import { LLM_PROVIDER, type LlmProvider } from '../llm-provider.interface';

/** What the Refiner needs to apply a chat instruction. */
export interface RefinementContext {
  instruction: string;
  current: RequirementDocument;
  idea: string;
  intent: IntentAnalysis | null;
}

/** The amended requirement document plus a human summary of what changed. */
export interface RefinementOutput {
  document: RequirementDocument;
  summary: string;
}

/**
 * Owns the post-generation chat (Slice 10): turns a natural-language instruction
 * into an amended Requirement Document. The downstream stages are regenerated by
 * the service afterwards, so this agent only needs to evolve the requirements.
 *
 * LLM-driven with a deterministic fallback that appends a requirement for the
 * instruction (and a scalability NFR when the instruction implies scale), so the
 * change cascades through the keyword-driven design fallbacks in mock mode.
 */
@Injectable()
export class RefinementAgent extends BaseAgent {
  readonly role = AgentRole.Refiner;

  private readonly logger = new Logger(RefinementAgent.name);

  protected readonly systemPrompt = [
    'You are the Solution Architect refining an existing software design.',
    'You receive the current Requirement Document (JSON) and one change request,',
    'and return the FULL updated Requirement Document plus a concise summary.',
    'Rules:',
    '- Apply ONLY what the change request implies; never drop or rewrite unrelated scope.',
    '- Support additions, modifications, AND removals: to remove something, delete',
    '  the relevant functional/non-functional/role/business-rule entries.',
    '- Keep existing ids stable; give new items fresh FR-/NFR-/BR- ids; never renumber.',
    '- Keep priorities (must/should/could) and NFR categories sensible and consistent.',
    '- If the request implies scale/traffic growth, add or tighten a scalability NFR.',
    '- summary: 1–3 short sentences stating the CONCRETE changes (what was added,',
    '  changed, or removed) — not a restatement of the request.',
  ].join('\n');

  constructor(@Inject(LLM_PROVIDER) llm: LlmProvider) {
    super(llm);
  }

  async refine(
    sessionId: string,
    ctx: RefinementContext,
  ): Promise<RefinementOutput> {
    const generatedAt = new Date().toISOString();
    try {
      const raw = await this.thinkJson<{
        document?: Partial<RequirementDocument>;
        summary?: string;
      }>(this.buildPrompt(ctx));
      if (this.isValid(raw?.document)) {
        return {
          document: {
            ...(raw!.document as RequirementDocument),
            sessionId,
            generatedAt,
          },
          summary:
            raw!.summary?.trim() ||
            `Applied your change: “${ctx.instruction}”.`,
        };
      }
      this.logger.debug('Refinement malformed; using deterministic amend.');
    } catch (err) {
      this.logger.warn(`Refinement failed; using fallback: ${err}`);
    }
    return this.buildDeterministic(sessionId, generatedAt, ctx);
  }

  private buildPrompt(ctx: RefinementContext): string {
    return [
      `Idea: ${ctx.idea}`,
      ctx.intent ? `Domain: ${ctx.intent.domain}` : '',
      '',
      'Current requirement document (JSON):',
      JSON.stringify(ctx.current),
      '',
      `Change request: ${ctx.instruction}`,
      '',
      'Return JSON: { "document": { functional[], nonFunctional[], roles[], ' +
        'businessRules[], constraints[], assumptions[] }, "summary": string }.',
    ]
      .filter(Boolean)
      .join('\n');
  }

  private isValid(doc: Partial<RequirementDocument> | undefined): boolean {
    return (
      !!doc &&
      Array.isArray(doc.functional) &&
      doc.functional.length > 0 &&
      Array.isArray(doc.nonFunctional) &&
      Array.isArray(doc.roles)
    );
  }

  // ── deterministic fallback ──────────────────────────────────────────────

  private buildDeterministic(
    sessionId: string,
    generatedAt: string,
    ctx: RefinementContext,
  ): RefinementOutput {
    const { current, instruction } = ctx;

    const functional: FunctionalRequirement[] = [
      ...current.functional,
      {
        id: `FR-${current.functional.length + 1}`,
        title: truncateTitle(instruction),
        description: instruction,
        priority: 'must',
      },
    ];

    const nonFunctional: NonFunctionalRequirement[] = [...current.nonFunctional];
    const changes = [`Added ${functional[functional.length - 1].id} for “${instruction}”.`];

    if (impliesScale(instruction)) {
      nonFunctional.push({
        id: `NFR-${current.nonFunctional.length + 1}`,
        category: 'scalability',
        // Phrase that trips the architecture fallback toward microservices.
        description: `${instruction} — must support millions of users with horizontal scaling, caching, and async processing.`,
      });
      changes.push(
        `Added ${nonFunctional[nonFunctional.length - 1].id} (scalability) and re-evaluated the architecture.`,
      );
    }

    const document: RequirementDocument = {
      ...current,
      sessionId,
      generatedAt,
      functional,
      nonFunctional,
    };

    return {
      document,
      summary: `${changes.join(' ')} Regenerated the system, database, and API designs to match.`,
    };
  }
}

function truncateTitle(text: string): string {
  const trimmed = text.trim();
  return trimmed.length <= 60 ? trimmed : `${trimmed.slice(0, 57)}…`;
}

/** Heuristic: does the instruction ask for more scale/capacity? */
function impliesScale(text: string): boolean {
  return /(scal|million|thousand|users|traffic|load|grow|throughput|concurrent|enterprise)/i.test(
    text,
  );
}
