import { Inject, Injectable } from '@nestjs/common';
import {
  AgentRole,
  significantTokens,
  type DegradedReason,
  type FunctionalRequirement,
  type IntentAnalysis,
  type NonFunctionalRequirement,
  type OutOfScopeItem,
  type RequirementDocument,
  untrustedField,
  screenRequirementDocument,
} from '@archivato/shared';
import { BaseAgent, degradedReasonFor } from '../agent.base';
import { LLM_PROVIDER, type LlmProvider } from '../llm-provider.interface';

/** What the Refiner needs to apply a chat instruction. */
export interface RefinementContext {
  instruction: string;
  current: RequirementDocument;
  idea: string;
  intent: IntentAnalysis | null;
}

/** The amended requirement document plus a human summary of what changed. */
export interface RefinementOutput {
  document: RequirementDocument;
  summary: string;
}

/**
 * Owns the post-generation chat (Slice 10): turns a natural-language instruction
 * into an amended Requirement Document. The downstream stages are regenerated by
 * the service afterwards, so this agent only needs to evolve the requirements.
 *
 * LLM-driven with a deterministic fallback that appends a requirement for the
 * instruction (and a scalability NFR when the instruction implies scale), so the
 * change cascades through the keyword-driven design fallbacks in mock mode.
 */
@Injectable()
export class RefinementAgent extends BaseAgent {
  readonly role = AgentRole.Refiner;

  protected readonly systemPrompt = [
    'You are the Solution Architect refining an existing software design.',
    'You receive the current Requirement Document (JSON) and one change request,',
    'and return the FULL updated Requirement Document plus a concise summary.',
    'Rules:',
    '- Apply ONLY what the change request implies; never drop or rewrite unrelated scope.',
    '- Support additions, modifications, AND removals: to remove something, delete',
    '  the relevant functional/non-functional/role/business-rule entries.',
    '- Keep existing ids stable; give new items fresh FR-/NFR-/BR- ids; never renumber.',
    '- Keep priorities (must/should/could) and NFR categories sensible and consistent.',
    '- If the request implies scale/traffic growth, add or tighten a scalability NFR.',
    '- New/changed requirements must stay atomic, testable, and consistent with the',
    '  existing document’s style, priorities, and terminology.',
    '- summary: 1–3 short sentences stating the CONCRETE changes (what was added,',
    '  changed, or removed) — not a restatement of the request.',
    'Output standard: return the COMPLETE updated document (not a diff) as strict',
    'JSON matching the schema, with every id numbered consistently and no dangling',
    'references.',
  ].join('\n');

  constructor(@Inject(LLM_PROVIDER) llm: LlmProvider) {
    super(llm);
  }

  /**
   * Amend the requirement document from a chat instruction.
   *
   * The result is screened exactly as a fresh generation is. This is a **second
   * write path to the same artifact**, and the artifact lands on the public share
   * page — so screening only at `RequirementEngineerAgent` would leave a refine
   * as the way around it: ask the model to "add the payment link back" (or let an
   * injection still sitting in the transcript do it) and the document is rewritten
   * unscreened.
   */
  async refine(
    sessionId: string,
    ctx: RefinementContext,
  ): Promise<RefinementOutput> {
    const output = await this.amend(sessionId, ctx);
    const { document, removed } = screenRequirementDocument(output.document);
    if (removed.length > 0) {
      this.logger.warn(
        `Refined requirement doc: stripped ${removed.length} link(s) — possible prompt injection: ${removed.join(', ')}`,
      );
    }
    return { ...output, document };
  }

  private async amend(
    sessionId: string,
    ctx: RefinementContext,
  ): Promise<RefinementOutput> {
    const generatedAt = new Date().toISOString();
    let degraded: DegradedReason = 'invalid_output';
    try {
      const raw = await this.thinkJson<{
        document?: Partial<RequirementDocument>;
        summary?: string;
      }>(this.buildPrompt(ctx));
      if (this.isValid(raw?.document)) {
        return {
          document: reconcileNarrative(
            {
              // Spread the current doc first so the model's amended arrays win but
              // any section it omitted (the R7 narrative fields — executive
              // summary, out-of-scope, assumptions & open questions) is preserved.
              ...ctx.current,
              ...(raw!.document as RequirementDocument),
              sessionId,
              generatedAt,
              // …but NOT the old provenance. Spreading `ctx.current` carries it,
              // and a refine rewrites the content, so an inherited stamp would
              // claim this text came from a run that never saw it — a doc refined
              // during an outage would still read "AI-generated".
              generation: this.provenance('llm'),
            },
            ctx.current,
          ),
          summary:
            raw!.summary?.trim() ||
            `Applied your change: “${ctx.instruction}”.`,
        };
      }
      this.logger.debug('Refinement malformed; using deterministic amend.');
    } catch (err) {
      degraded = degradedReasonFor(err);
      this.logger.warn(`Refinement failed (${degraded}); using fallback: ${err}`);
    }
    const fallback = this.buildDeterministic(sessionId, generatedAt, ctx);
    return {
      ...fallback,
      document: {
        ...fallback.document,
        generation: this.provenance('fallback', degraded),
      },
    };
  }

  private buildPrompt(ctx: RefinementContext): string {
    return [
      untrustedField('Idea', ctx.idea),
      ctx.intent ? `Domain: ${ctx.intent.domain}` : '',
      '',
      'Current requirement document (JSON):',
      JSON.stringify(ctx.current),
      '',
      `Change request: ${ctx.instruction}`,
      '',
      'Return JSON: { "document": { functional[], nonFunctional[], roles[], ' +
        'businessRules[], constraints[], assumptions[] }, "summary": string }.',
    ]
      .filter(Boolean)
      .join('\n');
  }

  private isValid(doc: Partial<RequirementDocument> | undefined): boolean {
    return (
      !!doc &&
      Array.isArray(doc.functional) &&
      doc.functional.length > 0 &&
      Array.isArray(doc.nonFunctional) &&
      Array.isArray(doc.roles)
    );
  }

  // ── deterministic fallback ──────────────────────────────────────────────

  private buildDeterministic(
    sessionId: string,
    generatedAt: string,
    ctx: RefinementContext,
  ): RefinementOutput {
    const { current, instruction } = ctx;

    const functional: FunctionalRequirement[] = [
      ...current.functional,
      {
        id: `FR-${current.functional.length + 1}`,
        title: truncateTitle(instruction),
        description: instruction,
        priority: 'must',
      },
    ];

    const nonFunctional: NonFunctionalRequirement[] = [...current.nonFunctional];
    const changes = [`Added ${functional[functional.length - 1].id} for “${instruction}”.`];

    if (impliesScale(instruction)) {
      nonFunctional.push({
        id: `NFR-${current.nonFunctional.length + 1}`,
        category: 'scalability',
        // Phrase that trips the architecture fallback toward microservices.
        description: `${instruction} — must support millions of users with horizontal scaling, caching, and async processing.`,
      });
      changes.push(
        `Added ${nonFunctional[nonFunctional.length - 1].id} (scalability) and re-evaluated the architecture.`,
      );
    }

    const document = reconcileNarrative(
      {
        ...current,
        sessionId,
        generatedAt,
        functional,
        nonFunctional,
      },
      current,
    );

    return {
      document,
      summary: `${changes.join(' ')} Regenerated the system, database, and API designs to match.`,
    };
  }
}

/**
 * Keep the refined document's client-facing narrative (R7) coherent:
 *  - the refine prompt never asks for the executive summary / out-of-scope /
 *    assumptions, so an empty value from the model must NOT blank out a section
 *    it wasn't touching — fall back to the pre-refine document;
 *  - drop any out-of-scope item the refine just brought INTO scope, so the
 *    document can't both promise and exclude the same capability.
 */
function reconcileNarrative(
  doc: RequirementDocument,
  current: RequirementDocument,
): RequirementDocument {
  const outOfScopeSource = doc.outOfScope?.length
    ? doc.outOfScope
    : current.outOfScope;
  return {
    ...doc,
    executiveSummary: doc.executiveSummary?.trim() || current.executiveSummary,
    outOfScope: pruneInScope(outOfScopeSource, doc.functional),
    assumptionsAndOpenQuestions: doc.assumptionsAndOpenQuestions?.length
      ? doc.assumptionsAndOpenQuestions
      : current.assumptionsAndOpenQuestions,
  };
}

/** Remove out-of-scope items now covered by a functional requirement. */
function pruneInScope(
  outOfScope: OutOfScopeItem[] | undefined,
  functional: FunctionalRequirement[],
): OutOfScopeItem[] | undefined {
  if (!outOfScope?.length) return outOfScope;
  const functionalText = functional.map((f) =>
    `${f.title} ${f.description}`.toLowerCase(),
  );
  return outOfScope.filter((item) => !isNowInScope(item.item, functionalText));
}

/**
 * True when an out-of-scope phrase is now covered by a functional requirement.
 * Conservative on purpose (≥2 shared significant tokens AND ≥60% of the phrase's
 * tokens) so an unrelated feature doesn't wrongly prune a real exclusion.
 */
function isNowInScope(phrase: string, functionalText: string[]): boolean {
  const tokens = significantTokens(phrase);
  if (tokens.length < 2) return false;
  return functionalText.some((text) => {
    const hits = tokens.filter((tkn) => text.includes(tkn)).length;
    return hits >= 2 && hits / tokens.length >= 0.6;
  });
}

/** Distinct lower-cased words of length ≥4 (drops filler like "the", "and"). */
function truncateTitle(text: string): string {
  const trimmed = text.trim();
  return trimmed.length <= 60 ? trimmed : `${trimmed.slice(0, 57)}…`;
}

/** Heuristic: does the instruction ask for more scale/capacity? */
function impliesScale(text: string): boolean {
  return /(scal|million|thousand|users|traffic|load|grow|throughput|concurrent|enterprise)/i.test(
    text,
  );
}
