/**
 * Operational proportionality, across every stage that recommends tooling.
 *
 * `scale-scenarios.spec.ts` proved the *architecture* is sized to the client's
 * numbers. It did not — and could not — see the second half of the bug: the
 * roadmap, QA plan, threat model and review each recommend infrastructure and
 * tooling of their own, none of them had ever been told a tier existed, and so
 * each one fell back on the prior the architect had just been cured of. The
 * reported symptom was a Hardening phase scheduling Prometheus and an ELK stack
 * for a five-figure MVP whose design had one process and one managed database.
 *
 * The two scenarios are imported, not re-declared, so "every stage agrees about
 * this project" is a claim about ONE project rather than two that happen to
 * match.
 *
 * Both directions are asserted. A change that only ever strips advanced tooling
 * passes half this file and is a different bug — an enterprise platform with no
 * centralized logging is an outage nobody can diagnose.
 */

import type {
  ApiDesign,
  DatabaseDesign,
  RequirementDocument,
  SystemDesign,
} from '@archivato/shared';
import { SystemArchitectAgent } from './system-architect.agent';
import { DatabaseDesignerAgent } from './database-designer.agent';
import { ApiDesignerAgent } from './api-designer.agent';
import { RoadmapPlannerAgent } from './roadmap-planner.agent';
import { QaPlannerAgent } from './qa-planner.agent';
import { ThreatModelerAgent } from './threat-modeler.agent';
import { ReviewerAgent } from './reviewer.agent';
import { MockLlmProvider } from '../mock-llm.provider';
import type { LlmProvider } from '../llm-provider.interface';
import {
  CLINIC_IDEA,
  clinicRequirements,
  clinicSlots,
  TASK_BOARD_IDEA,
  taskBoardRequirements,
  taskBoardSlots,
} from './scale-scenarios.fixtures';

jest.setTimeout(30_000);

/** Every artifact a downstream stage reads, generated by the real agents. */
interface Pipeline {
  requirements: RequirementDocument;
  systemDesign: SystemDesign;
  databaseDesign: DatabaseDesign;
  apiDesign: ApiDesign;
}

async function buildPipeline(
  id: string,
  idea: string,
  requirements: RequirementDocument,
  slots: ReturnType<typeof taskBoardSlots>,
): Promise<Pipeline> {
  const llm = new MockLlmProvider();
  const systemDesign = await new SystemArchitectAgent(llm).generate(id, {
    idea,
    intent: null,
    requirements,
    slots,
  });
  const databaseDesign = await new DatabaseDesignerAgent(llm).generate(id, {
    idea,
    intent: null,
    requirements,
    systemDesign,
  });
  const apiDesign = await new ApiDesignerAgent(llm).generate(id, {
    idea,
    intent: null,
    requirements,
    systemDesign,
    databaseDesign,
  });
  return { requirements, systemDesign, databaseDesign, apiDesign };
}

const downstreamCtx = (idea: string, p: Pipeline) => ({ idea, intent: null, ...p });

/** Every string a stage's artifact puts in front of the owner, lowercased. */
const roadmapText = (r: Awaited<ReturnType<RoadmapPlannerAgent['generate']>>) =>
  r.phases
    .flatMap((p) => [
      p.name,
      p.goal,
      ...p.milestones.flatMap((m) => [
        m.title,
        ...m.tasks.flatMap((t) => [t.title, t.detail ?? '']),
      ]),
    ])
    .join(' ')
    .toLowerCase();

/** Records every prompt sent, then returns nothing so the fallback path runs. */
function recordingLlm(): { llm: LlmProvider; prompts: () => string } {
  const seen: string[] = [];
  const llm = {
    name: 'recording',
    complete: async () => '{}',
    completeJson: async (messages: unknown) => {
      seen.push(JSON.stringify(messages));
      return {} as never;
    },
  } as unknown as LlmProvider;
  return { llm, prompts: () => seen.join('\n') };
}

// ── scenario A: the reported small MVP ──────────────────────────────────────

describe('small tier: the reported lightweight task board', () => {
  let pipeline: Pipeline;

  beforeAll(async () => {
    pipeline = await buildPipeline(
      's1',
      TASK_BOARD_IDEA,
      taskBoardRequirements(),
      taskBoardSlots(),
    );
    // Guards every assertion below: if the architect ever stopped reading this
    // project as small, the rest of the file would pass for the wrong reason.
    expect(pipeline.systemDesign.scaleTier).toBe('small');
  });

  it('plans observability the team can actually run, not a monitoring platform', async () => {
    const roadmap = await new RoadmapPlannerAgent(new MockLlmProvider()).generate(
      's1',
      downstreamCtx(TASK_BOARD_IDEA, pipeline),
    );
    const text = roadmapText(roadmap);

    // The reported output, gone.
    expect(text).not.toContain('prometheus');
    expect(text).not.toContain('elk');
    expect(text).not.toContain('grafana');
    expect(text).not.toContain('datadog');
    // …and replaced by something, not merely deleted. A plan with no
    // observability at all is a different wrong answer.
    expect(text).toMatch(/health|log/);
  });

  it('does not schedule work on infrastructure the design does not have', async () => {
    // The offline path had the bug more sharply than the model did: it scheduled
    // "Add caching for read-heavy endpoints" on a design the tier had just
    // stripped the cache from — the plan contradicting the architecture inside
    // one package.
    const roadmap = await new RoadmapPlannerAgent(new MockLlmProvider()).generate(
      's1',
      downstreamCtx(TASK_BOARD_IDEA, pipeline),
    );
    const stack = pipeline.systemDesign.techStack
      .map((t) => `${t.layer} ${t.technology}`)
      .join(' ')
      .toLowerCase();

    expect(stack).not.toContain('redis');
    expect(roadmapText(roadmap)).not.toContain('caching');
  });

  it('recommends QA tooling proportional to the tier', async () => {
    const plan = await new QaPlannerAgent(new MockLlmProvider()).generate(
      's1',
      downstreamCtx(TASK_BOARD_IDEA, pipeline),
    );
    const tooling = plan.tooling.join(' ').toLowerCase();

    expect(tooling).not.toContain('testcontainers');
    // The testing base itself is never cut — that would be cutting testing, not
    // cutting scale.
    expect(tooling).toMatch(/jest|test runner/);
    expect(tooling).toMatch(/playwright|cypress/);
  });

  it('mitigates threats with controls this team can operate', async () => {
    const model = await new ThreatModelerAgent(new MockLlmProvider()).generate(
      's1',
      downstreamCtx(TASK_BOARD_IDEA, pipeline),
    );
    const mitigations = model.threats.map((t) => t.mitigation.toLowerCase());

    // A WAF is a product to buy and tune; recommending one here produces a
    // mitigation nobody implements, which reads as done and leaves the threat open.
    expect(mitigations.some((m) => m.includes('waf'))).toBe(false);
    // The threat is still raised — severity never scales down with the budget.
    expect(model.threats.some((t) => t.category === 'denial_of_service')).toBe(true);
    // And the security controls that ARE free still appear.
    expect(mitigations.join(' ')).toContain('rate limit');
  });

  it('does not tell a queue-less design it is missing a queue', async () => {
    const model = await new ThreatModelerAgent(new MockLlmProvider()).generate(
      's1',
      downstreamCtx(TASK_BOARD_IDEA, pipeline),
    );
    const dos = model.threats
      .filter((t) => t.category === 'denial_of_service')
      .map((t) => t.mitigation.toLowerCase())
      .join(' ');

    expect(dos).not.toContain('background queue');
  });

  it('does not review a correctly-sized design as under-built', async () => {
    // The worst of the four: the review adjudicates the other artifacts, and it
    // was marking the design down on two axes for the simplicity the architect
    // was instructed to choose — then offering a `patch` that would write Redis
    // straight back into the tech stack.
    const review = await new ReviewerAgent(new MockLlmProvider()).generate(
      's1',
      downstreamCtx(TASK_BOARD_IDEA, pipeline),
    );
    const titles = [
      ...review.scalabilityIssues,
      ...review.performanceRisks,
      ...review.costOptimizations,
    ].map((f) => f.title.toLowerCase());

    expect(titles).not.toContain('no caching layer');
    expect(titles).not.toContain('no asynchronous processing');
    expect(titles).not.toContain('add a caching layer');
    expect(review.recommendations.join(' ').toLowerCase()).not.toContain(
      'caching layer',
    );
  });

  it('does not depress the scalability score for right-sized simplicity', async () => {
    const review = await new ReviewerAgent(new MockLlmProvider()).generate(
      's1',
      downstreamCtx(TASK_BOARD_IDEA, pipeline),
    );
    // The absent queue and cache were worth 18 points between them, so a
    // correctly-sized design used to score mid-60s for doing the right thing.
    expect(review.scores.scalability).toBeGreaterThanOrEqual(80);
  });
});

// ── scenario B: the enterprise counterweight ────────────────────────────────

describe('large tier: the multi-branch clinic platform', () => {
  let pipeline: Pipeline;

  beforeAll(async () => {
    pipeline = await buildPipeline(
      's2',
      CLINIC_IDEA,
      clinicRequirements(),
      clinicSlots(),
    );
    expect(pipeline.systemDesign.scaleTier).toBe('large');
  });

  it('STILL plans real observability — the fix calibrates both ways', async () => {
    const roadmap = await new RoadmapPlannerAgent(new MockLlmProvider()).generate(
      's2',
      downstreamCtx(CLINIC_IDEA, pipeline),
    );
    const text = roadmapText(roadmap);

    expect(text).toContain('tracing');
    expect(text).toContain('caching');
  });

  it('STILL recommends the heavier QA toolchain', async () => {
    const plan = await new QaPlannerAgent(new MockLlmProvider()).generate(
      's2',
      downstreamCtx(CLINIC_IDEA, pipeline),
    );
    const tooling = plan.tooling.join(' ').toLowerCase();

    expect(tooling).toContain('testcontainers');
    expect(tooling).toContain('load testing');
  });

  it('STILL recommends edge security infrastructure', async () => {
    const model = await new ThreatModelerAgent(new MockLlmProvider()).generate(
      's2',
      downstreamCtx(CLINIC_IDEA, pipeline),
    );
    const mitigations = model.threats.map((t) => t.mitigation.toLowerCase()).join(' ');

    expect(mitigations).toContain('waf');
  });

  it('keeps the backstop off entirely above the small tier', async () => {
    // A large-tier plan that names a monitoring platform must survive verbatim.
    const mock = new MockLlmProvider();
    mock.enqueueJson({
      summary: 'plan',
      phases: [
        {
          name: 'Hardening & Launch',
          goal: 'Production readiness.',
          dependsOn: [],
          moduleNames: [],
          milestones: [
            {
              title: 'Monitoring & Logging',
              tasks: [
                { title: 'Integrate Prometheus metrics', detail: 'Expose /metrics endpoint' },
                { title: 'Centralized logging', detail: 'Send logs to ELK stack' },
              ],
            },
          ],
        },
      ],
    });

    const roadmap = await new RoadmapPlannerAgent(mock).generate(
      's2',
      downstreamCtx(CLINIC_IDEA, pipeline),
    );
    expect(roadmapText(roadmap)).toContain('prometheus');
  });
});

// ── the backstop, on the path that actually shipped the bug ─────────────────

describe('the roadmap backstop (LLM path, small tier)', () => {
  async function smallPipeline(): Promise<Pipeline> {
    return buildPipeline('s1', TASK_BOARD_IDEA, taskBoardRequirements(), taskBoardSlots());
  }

  /** The exact milestone the user reported, verbatim. */
  const reportedPhase = {
    name: 'Hardening & Launch',
    goal: 'Production readiness.',
    dependsOn: [],
    moduleNames: [],
    milestones: [
      {
        title: 'Monitoring & Logging',
        tasks: [
          { title: 'Integrate Prometheus metrics', detail: 'Expose /metrics endpoint' },
          { title: 'Centralized logging', detail: 'Send logs to ELK stack' },
        ],
      },
    ],
  };

  it('replaces an emptied observability milestone rather than deleting it', async () => {
    const pipeline = await smallPipeline();
    const mock = new MockLlmProvider();
    mock.enqueueJson({ summary: 'plan', phases: [reportedPhase] });

    const roadmap = await new RoadmapPlannerAgent(mock).generate(
      's1',
      downstreamCtx(TASK_BOARD_IDEA, pipeline),
    );
    const milestone = roadmap.phases[0].milestones[0];

    expect(milestone.title).toBe('Monitoring & Logging');
    // Deleting both tasks would have left a plan with no observability at all.
    expect(milestone.tasks).toHaveLength(1);
    expect(milestone.tasks[0].title.toLowerCase()).toMatch(/log|health/);
    expect(roadmapText(roadmap)).not.toContain('prometheus');
  });

  it('leaves a milestone alone when proportional tasks survive alongside', async () => {
    const pipeline = await smallPipeline();
    const mock = new MockLlmProvider();
    mock.enqueueJson({
      summary: 'plan',
      phases: [
        {
          ...reportedPhase,
          milestones: [
            {
              title: 'Monitoring & Logging',
              tasks: [
                { title: 'Add a /health endpoint' },
                { title: 'Ship logs to a Grafana Loki cluster' },
              ],
            },
          ],
        },
      ],
    });

    const roadmap = await new RoadmapPlannerAgent(mock).generate(
      's1',
      downstreamCtx(TASK_BOARD_IDEA, pipeline),
    );
    const tasks = roadmap.phases[0].milestones[0].tasks.map((t) => t.title);

    expect(tasks).toEqual(['Add a /health endpoint']);
  });

  it('does not strip a search task that merely names a search engine', async () => {
    // The backstop walks EVERY phase, not just Hardening. A Supporting Features
    // task indexing products for search is not an operations recommendation, and
    // an over-broad pattern would silently delete real scope.
    const pipeline = await smallPipeline();
    const mock = new MockLlmProvider();
    mock.enqueueJson({
      summary: 'plan',
      phases: [
        {
          name: 'Supporting features',
          goal: 'Search.',
          dependsOn: [],
          moduleNames: [],
          milestones: [
            {
              title: 'Search',
              tasks: [{ title: 'Index tasks in Elasticsearch for full-text search' }],
            },
          ],
        },
      ],
    });

    const roadmap = await new RoadmapPlannerAgent(mock).generate(
      's1',
      downstreamCtx(TASK_BOARD_IDEA, pipeline),
    );
    expect(roadmapText(roadmap)).toContain('elasticsearch');
  });

  it('keeps heavier tooling when a requirement genuinely demands assurance', async () => {
    // The escape hatch in the prompt and the escape hatch in the code are the
    // same test, so the two can never disagree about when heavier tooling is
    // warranted.
    const base = await smallPipeline();
    const pipeline: Pipeline = {
      ...base,
      requirements: {
        ...base.requirements,
        nonFunctional: [
          ...base.requirements.nonFunctional,
          {
            id: 'NFR-3',
            category: 'availability',
            description: 'The contract commits to a 99.9% uptime target with monthly reporting.',
          },
        ],
      },
    };
    const mock = new MockLlmProvider();
    mock.enqueueJson({ summary: 'plan', phases: [reportedPhase] });

    const roadmap = await new RoadmapPlannerAgent(mock).generate(
      's1',
      downstreamCtx(TASK_BOARD_IDEA, pipeline),
    );
    expect(roadmapText(roadmap)).toContain('prometheus');
  });
});

// ── one tier, four prompts ──────────────────────────────────────────────────

describe('every downstream stage is told the same tier', () => {
  it('sends one identical verdict to roadmap, QA, threat model and review', async () => {
    const pipeline = await buildPipeline(
      's1',
      TASK_BOARD_IDEA,
      taskBoardRequirements(),
      taskBoardSlots(),
    );
    const ctx = downstreamCtx(TASK_BOARD_IDEA, pipeline);

    const sent: string[] = [];
    for (const run of [
      (llm: LlmProvider) => new RoadmapPlannerAgent(llm).generate('s1', ctx),
      (llm: LlmProvider) => new QaPlannerAgent(llm).generate('s1', ctx),
      (llm: LlmProvider) => new ThreatModelerAgent(llm).generate('s1', ctx),
      (llm: LlmProvider) => new ReviewerAgent(llm).generate('s1', ctx),
    ]) {
      const { llm, prompts } = recordingLlm();
      await run(llm);
      sent.push(prompts());
    }

    for (const prompt of sent) {
      expect(prompt).toContain('SCALE TIER: SMALL');
      expect(prompt).toContain('OPERATIONS BUDGET (Small/MVP tier)');
      // The escape hatch travels with the prohibition, or the model reads the
      // rule as absolute and drops assurance work a contract requires.
      expect(prompt).toContain('The ONLY exception');
    }
  });

  it('sends the large budget when the project is large', async () => {
    const pipeline = await buildPipeline(
      's2',
      CLINIC_IDEA,
      clinicRequirements(),
      clinicSlots(),
    );
    const { llm, prompts } = recordingLlm();
    await new RoadmapPlannerAgent(llm).generate(
      's2',
      downstreamCtx(CLINIC_IDEA, pipeline),
    );

    const sent = prompts();
    expect(sent).toContain('SCALE TIER: LARGE');
    expect(sent).toContain('Large/Enterprise tier');
    expect(sent).not.toContain('Do NOT introduce a dedicated observability stack');
  });

  it('sends no tier block at all for a design generated before tiers existed', async () => {
    // An absent tier means the previous behaviour — the same rule as an
    // unstamped sourceStamp never reading as stale. Guessing one here would size
    // a plan from an assessment nobody made.
    const pipeline = await buildPipeline(
      's1',
      TASK_BOARD_IDEA,
      taskBoardRequirements(),
      taskBoardSlots(),
    );
    const legacy: Pipeline = {
      ...pipeline,
      systemDesign: { ...pipeline.systemDesign, scaleTier: undefined },
    };
    const { llm, prompts } = recordingLlm();
    await new RoadmapPlannerAgent(llm).generate(
      's1',
      downstreamCtx(TASK_BOARD_IDEA, legacy),
    );

    expect(prompts()).not.toContain('SCALE TIER');
  });
});
