import type { Metadata } from 'next';
import { siteName, siteUrl } from '@/lib/site';
import { SharedProjectView } from '@/components/share/SharedProjectView';
import { DEMO_PATH, DEMO_SCOPING_PACKAGE, DEMO_TITLE } from '@/lib/demo-scoping-package';

/**
 * The public demo: a complete client scoping package, exactly as a client
 * receives it.
 *
 * **Why this page exists.** The landing page can only *describe* the output; the
 * output is the product. A prospect evaluating us is a dev-shop owner asking one
 * question — "is what this sends my client good enough to put my name on?" — and
 * nothing answers that except the artifact itself. Before this, the only way to
 * see one was to sign up, run an interview, and generate. That is a lot of work
 * to ask of someone who is still deciding.
 *
 * **Why it reuses the real share page.** It renders `SharedProjectView` with the
 * same fixture the in-app example tour uses, redacted by the same rules
 * `ShareService.view` applies. So the demo cannot become a lie: there is no
 * separate "marketing version" of the artifact to drift out of sync, and if the
 * share page regresses, this regresses visibly with it.
 *
 * **It lives outside the `(app)` route group** — like the landing and share
 * pages — so a cold visitor doesn't download and hydrate the authenticated app
 * (auth form, account menu, notification bell, billing dialog) just to read a
 * document. Don't move it in, and don't import app chrome here.
 *
 * **Unlike `/s/<token>`, this one is INDEXABLE.** A real share link is unlisted
 * because it holds someone's business idea; this holds a fictional one that we
 * wrote to be seen, and it's the page that earns the "client scoping" keyword
 * (POSITIONING §4.7) with something more useful than marketing copy.
 */

const DESCRIPTION =
  'A complete client scoping package generated by Archivato — scope, architecture, cost estimate and delivery plan — exactly as a client receives it.';

export const metadata: Metadata = {
  title: 'Demo: a complete client scoping package',
  description: DESCRIPTION,
  alternates: { canonical: `${siteUrl}${DEMO_PATH}` },
  // Indexable on purpose — see the note above. This is the opposite of the
  // `noindex` on /s/[token], and the difference is consent: that page is
  // someone's real idea, this one is ours to publish.
  robots: { index: true, follow: true },
  openGraph: {
    title: `Demo: ${DEMO_TITLE}`,
    description: DESCRIPTION,
    url: `${siteUrl}${DEMO_PATH}`,
    siteName,
    type: 'article',
  },
  twitter: {
    card: 'summary_large_image',
    title: `Demo: ${DEMO_TITLE}`,
    description: DESCRIPTION,
  },
};

export default function DemoScopingPackagePage() {
  return (
    <main>
      <SharedProjectView project={DEMO_SCOPING_PACKAGE} />
    </main>
  );
}
