'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Compass } from 'lucide-react';
import type { BusinessAnalysis } from '@archivato/shared';
import { businessAnalysisApi } from '@/lib/api';
import { Button } from '@/components/ui/button';
import { ArtifactSkeleton } from '@/components/shared/ArtifactSkeleton';
import { EmptyState } from '@/components/shared/EmptyState';
import { BusinessAnalysisView } from '@/components/product/BusinessAnalysisView';
import { useToast } from '@/components/shared/toast';
import { GenerationNotice } from '@/components/project/GenerationNotice';

/**
 * The Business Analysis stage tab. Runs off the confirmed interview and feeds
 * the Requirement Engineer, but does not gate it — so this panel is reachable
 * the moment the interview is confirmed, and a project that never runs it still
 * generates requirements normally.
 *
 * Because the analysis is the discovery layer that grounds the requirement doc,
 * the post-interview flow lands here and generates it FIRST (`autoGenerate`),
 * before the owner moves on to Requirements. The panel owns its own generation
 * (unlike the pipeline stages the dashboard drives), so the auto-kick lives here.
 */
export function BusinessAnalysisPanel({
  sessionId,
  reloadKey,
  autoGenerate = false,
  onAutoGenerated,
}: {
  sessionId: string;
  /** Bump to refetch (e.g. after a restore). */
  reloadKey: number;
  /**
   * One-shot signal to generate on first view when no analysis exists yet —
   * set right after the interview is confirmed. The panel fires it at most once
   * (a ref guards re-runs) and calls `onAutoGenerated` the instant it starts, so
   * the parent can drop the flag before a tab-switch remount could re-trigger it.
   */
  autoGenerate?: boolean;
  onAutoGenerated?: () => void;
}) {
  const toast = useToast();
  const { t } = useTranslation('stages');
  const [analysis, setAnalysis] = useState<BusinessAnalysis | null>(null);
  const [loaded, setLoaded] = useState(false);
  const [busy, setBusy] = useState(false);
  const autoFired = useRef(false);

  const load = useCallback(async () => {
    try {
      setAnalysis(await businessAnalysisApi.get(sessionId));
    } catch {
      setAnalysis(null); // 404 = not generated yet
    } finally {
      setLoaded(true);
    }
  }, [sessionId]);

  useEffect(() => {
    void load();
  }, [load, reloadKey]);

  const generate = useCallback(async () => {
    setBusy(true);
    try {
      setAnalysis(await businessAnalysisApi.generate(sessionId));
      toast({ title: t('business.generatedToast'), variant: 'success' });
    } catch (e) {
      toast({
        title: t('business.failed'),
        description: e instanceof Error ? e.message : String(e),
        variant: 'error',
      });
    } finally {
      setBusy(false);
    }
  }, [sessionId, toast, t]);

  // Auto-generate once on first view after confirmation. Guarded so it can only
  // fire when there is genuinely nothing to show, and only a single time.
  useEffect(() => {
    if (!autoGenerate || !loaded || analysis || busy || autoFired.current) return;
    autoFired.current = true;
    onAutoGenerated?.();
    void generate();
  }, [autoGenerate, loaded, analysis, busy, generate, onAutoGenerated]);

  if (!loaded || (busy && !analysis)) return <ArtifactSkeleton />;

  if (!analysis) {
    return (
      <EmptyState
        icon={Compass}
        title={t('business.emptyTitle')}
        description={t('business.emptyDescription')}
      >
        <Button onClick={generate} disabled={busy}>
          {busy ? t('business.working') : t('business.generate')}
        </Button>
      </EmptyState>
    );
  }

  return (
    <div className="space-y-3">
      <GenerationNotice
        generation={analysis.generation}
        busy={busy}
        onRegenerate={generate}
      />
      <BusinessAnalysisView analysis={analysis} />
      <Button variant="secondary" onClick={generate} disabled={busy}>
        {busy ? t('business.working') : t('business.regenerate')}
      </Button>
    </div>
  );
}
