import { render, screen, waitFor } from '@testing-library/react';
import { BusinessAnalysisPanel } from './BusinessAnalysisPanel';

// Chrome-only: identity `t` keeps assertions on behavior, not copy.
jest.mock('react-i18next', () => ({
  useTranslation: () => ({ t: (key: string) => key }),
}));

const getMock = jest.fn();
const generateMock = jest.fn();
jest.mock('@/lib/api', () => ({
  businessAnalysisApi: {
    get: (...args: unknown[]) => getMock(...args),
    generate: (...args: unknown[]) => generateMock(...args),
  },
}));

jest.mock('@/components/shared/toast', () => ({ useToast: () => jest.fn() }));
jest.mock('@/components/product/BusinessAnalysisView', () => ({
  BusinessAnalysisView: () => <div data-testid="analysis-view" />,
}));
jest.mock('@/components/project/GenerationNotice', () => ({
  GenerationNotice: () => null,
}));

beforeEach(() => {
  getMock.mockReset();
  generateMock.mockReset();
});

describe('BusinessAnalysisPanel auto-generation (post-interview flow)', () => {
  it('generates the analysis on first view when autoGenerate is set and none exists', async () => {
    getMock.mockRejectedValue(new Error('404')); // not generated yet
    generateMock.mockResolvedValue({ generation: undefined });
    const onAutoGenerated = jest.fn();

    render(
      <BusinessAnalysisPanel
        sessionId="s1"
        reloadKey={0}
        autoGenerate
        onAutoGenerated={onAutoGenerated}
      />,
    );

    await waitFor(() => expect(generateMock).toHaveBeenCalledTimes(1));
    // The parent flag is dropped the instant it fires, so a remount can't re-run it.
    expect(onAutoGenerated).toHaveBeenCalledTimes(1);
    expect(await screen.findByTestId('analysis-view')).toBeInTheDocument();
  });

  it('does not auto-generate when the flag is off (manual path)', async () => {
    getMock.mockRejectedValue(new Error('404'));

    render(<BusinessAnalysisPanel sessionId="s1" reloadKey={0} />);

    // Wait for the empty state's Generate button, then confirm nothing fired.
    expect(await screen.findByText('business.generate')).toBeInTheDocument();
    expect(generateMock).not.toHaveBeenCalled();
  });

  it('does not regenerate when an analysis already exists', async () => {
    getMock.mockResolvedValue({ generation: undefined }); // already generated

    render(<BusinessAnalysisPanel sessionId="s1" reloadKey={0} autoGenerate />);

    expect(await screen.findByTestId('analysis-view')).toBeInTheDocument();
    expect(generateMock).not.toHaveBeenCalled();
  });
});
