/** BullMQ queue + job names for async pipeline generation. */
export const PIPELINE_QUEUE = 'pipeline';
export const GENERATE_JOB = 'generate';

/** Payload carried by every generation job. */
export interface GenerateJobData {
  sessionId: string;
  stage: import('@archivato/shared').PipelineStageName;
  /**
   * Who enqueued it. The worker runs off the request thread, so this is the only
   * way LLM usage generated by a job can be attributed to a user. Optional so a
   * job enqueued before this field existed still processes.
   */
  userId?: string;
}
