import {
  BadGatewayException,
  BadRequestException,
  ConflictException,
  Injectable,
  Logger,
  UnauthorizedException,
} from '@nestjs/common';
import JSZip from 'jszip';
import {
  buildScaffold,
  DEFAULT_SCAFFOLD_TARGET,
  type GithubPushResult,
  type ScaffoldFile,
  type ScaffoldManifest,
  type ScaffoldTarget,
} from '@archivato/shared';
import { ExportService } from '../export/export.service';
import { GithubConnectionService } from './github-connection.service';
import type { PushToGithubDto } from './dto/push-to-github.dto';

const GITHUB_API = 'https://api.github.com';

@Injectable()
export class ScaffoldService {
  private readonly logger = new Logger(ScaffoldService.name);

  constructor(
    private readonly exporter: ExportService,
    private readonly connection: GithubConnectionService,
  ) {}

  /** Build the scaffold file set from the confirmed design bundle. */
  private async files(
    sessionId: string,
    target: ScaffoldTarget,
  ): Promise<ScaffoldFile[]> {
    // bundle() enforces the "pipeline complete through API design" gate (409).
    const bundle = await this.exporter.bundle(sessionId);
    return buildScaffold(
      {
        idea: bundle.idea.idea,
        systemDesign: bundle.systemDesign,
        databaseDesign: bundle.databaseDesign,
        apiDesign: bundle.apiDesign,
      },
      target,
    );
  }

  /** File manifest (paths + contents) — powers the UI file list. */
  async manifest(
    sessionId: string,
    target: ScaffoldTarget = DEFAULT_SCAFFOLD_TARGET,
  ): Promise<ScaffoldManifest> {
    const files = await this.files(sessionId, target);
    return {
      sessionId,
      generatedAt: new Date().toISOString(),
      target,
      fileCount: files.length,
      files,
    };
  }

  /** The scaffold as a .zip archive (Buffer). */
  async zip(
    sessionId: string,
    target: ScaffoldTarget = DEFAULT_SCAFFOLD_TARGET,
  ): Promise<Buffer> {
    const files = await this.files(sessionId, target);
    const archive = new JSZip();
    for (const file of files) archive.file(file.path, file.content);
    return archive.generateAsync({ type: 'nodebuffer' });
  }

  /**
   * Create a new GitHub repository and commit the whole scaffold onto it.
   *
   * The repo is created with `auto_init: true` on purpose: GitHub's Git Data API
   * refuses to build a tree on a truly EMPTY repo ("409 Git Repository is
   * empty"), so we let GitHub make an initial commit + `main` branch first, then
   * layer our files on top: read the base commit → create a tree of our files →
   * commit with the base as parent → fast-forward `main`. Token is a PAT (used
   * once) or the user's stored OAuth connection.
   */
  async pushToGithub(
    sessionId: string,
    userId: string,
    dto: PushToGithubDto,
  ): Promise<GithubPushResult> {
    const files = await this.files(sessionId, dto.target ?? DEFAULT_SCAFFOLD_TARGET);
    const token = dto.token ?? (await this.connection.resolveToken(userId));
    if (!token) {
      throw new BadRequestException(
        'Connect your GitHub account or provide a token first.',
      );
    }

    // 1) Create the repository, initialized so it has a commit + default branch.
    const repo = await this.gh<{
      full_name: string;
      html_url: string;
      owner: { login: string };
      name: string;
      default_branch: string;
    }>(token, 'POST', '/user/repos', {
      name: dto.repoName,
      private: dto.isPrivate ?? true,
      auto_init: true,
      description: 'Generated by Archivato AI Builder',
    });
    const owner = repo.owner.login;
    const name = repo.name;
    const branch = repo.default_branch || 'main';
    const base = `/repos/${owner}/${name}`;

    // 2) The initial commit sha (the parent for our commit). May lag a moment
    //    after creation — gh() retries the transient 404/409.
    const ref = await this.gh<{ object: { sha: string } }>(
      token,
      'GET',
      `${base}/git/ref/heads/${branch}`,
    );
    const baseSha = ref.object.sha;

    // 3) A tree of our files (no base_tree → replaces the auto-init README).
    const tree = await this.gh<{ sha: string }>(token, 'POST', `${base}/git/trees`, {
      tree: files.map((f) => ({
        path: f.path,
        mode: '100644',
        type: 'blob',
        content: f.content,
      })),
    });

    // 4) A commit on top of the initial commit.
    const commit = await this.gh<{ sha: string }>(
      token,
      'POST',
      `${base}/git/commits`,
      {
        message: 'Initial scaffold from Archivato AI Builder',
        tree: tree.sha,
        parents: [baseSha],
      },
    );

    // 5) Fast-forward the default branch to our commit.
    await this.gh(token, 'PATCH', `${base}/git/refs/heads/${branch}`, {
      sha: commit.sha,
      force: true,
    });

    return { htmlUrl: repo.html_url, repo: repo.full_name, branch };
  }

  /**
   * Minimal GitHub REST client (native fetch). Maps failures to sanitized HTTP
   * errors and never surfaces the token. GitHub error bodies are logged
   * server-side (without the token) for diagnostics.
   */
  private async gh<T = unknown>(
    token: string,
    method: string,
    path: string,
    body?: unknown,
  ): Promise<T> {
    // Two classes of transient failure are retried with backoff:
    //  1. Network errors (e.g. UND_ERR_CONNECT_TIMEOUT on a flaky path) — they
    //     happen before the request is sent, so retrying can't duplicate work.
    //  2. Transient HTTP statuses right after repo creation: GitHub provisions
    //     a new repo's git backend asynchronously, so an immediate git/trees
    //     call often returns 404/409 until it's ready (5xx likewise). Retrying
    //     these is what makes the initial push reliable.
    const maxAttempts = 5;
    let lastStatus = 0;
    let lastDetail = '';
    for (let attempt = 1; attempt <= maxAttempts; attempt++) {
      let res: Response;
      try {
        res = await fetch(`${GITHUB_API}${path}`, {
          method,
          headers: {
            Authorization: `Bearer ${token}`,
            Accept: 'application/vnd.github+json',
            'X-GitHub-Api-Version': '2022-11-28',
            'User-Agent': 'Archivato-AI-Builder',
            'Content-Type': 'application/json',
          },
          body: body === undefined ? undefined : JSON.stringify(body),
        });
      } catch (err) {
        // Node's fetch throws a generic "fetch failed"; the real reason (DNS,
        // TLS, ECONNRESET, timeout…) lives on `err.cause`.
        const e = err as Error & { cause?: { message?: string; code?: string } };
        const reason = e.cause?.code ?? e.cause?.message ?? e.message;
        if (attempt < maxAttempts) {
          this.logger.warn(
            `GitHub ${method} ${path} network error (attempt ${attempt}/${maxAttempts}): ${reason} — retrying`,
          );
          await this.backoff(attempt);
          continue;
        }
        this.logger.error(
          `GitHub ${method} ${path} could not be reached after ${maxAttempts} attempts: ${reason}`,
        );
        throw new BadGatewayException('Could not reach GitHub. Try again.');
      }

      if (res.ok) {
        return (await res.json().catch(() => ({}))) as T;
      }

      const detail = await res.text().catch(() => '');
      lastStatus = res.status;
      lastDetail = detail;
      const ghMessage = extractGithubMessage(detail);

      // Deterministic auth/validation failures — never retry these.
      if (res.status === 401) {
        this.logger.error(`GitHub ${method} ${path} → 401`);
        throw new UnauthorizedException('GitHub token is invalid or expired.');
      }
      if (res.status === 403) {
        this.logger.error(`GitHub ${method} ${path} → 403: ${detail}`);
        throw new UnauthorizedException(
          `GitHub denied the request (403): ${ghMessage}`,
        );
      }
      if (res.status === 422) {
        this.logger.error(`GitHub ${method} ${path} → 422: ${detail}`);
        throw new ConflictException(
          `GitHub rejected the request (422): ${ghMessage}`,
        );
      }

      // Transient: a new repo's git backend not ready yet (404/409) or a GitHub
      // hiccup (5xx). Retry with backoff before giving up.
      const retryable =
        res.status === 404 || res.status === 409 || res.status >= 500;
      if (retryable && attempt < maxAttempts) {
        this.logger.warn(
          `GitHub ${method} ${path} → ${res.status} (attempt ${attempt}/${maxAttempts}): ${ghMessage} — retrying`,
        );
        await this.backoff(attempt);
        continue;
      }

      this.logger.error(`GitHub ${method} ${path} → ${res.status}: ${detail}`);
      throw new BadGatewayException(
        `GitHub error ${res.status} on ${shortGitPath(path)}: ${ghMessage}`,
      );
    }

    // Exhausted retries without returning.
    throw new BadGatewayException(
      `GitHub kept failing (${lastStatus}) on ${shortGitPath(path)}: ${extractGithubMessage(lastDetail)}`,
    );
  }

  /** Exponential-ish backoff (0.6s, 1.2s, 1.8s, …) between retries. */
  private backoff(attempt: number): Promise<void> {
    return new Promise((r) => setTimeout(r, 600 * attempt));
  }
}

/** Pull GitHub's human message out of an error body (JSON `{message}` or raw). */
function extractGithubMessage(detail: string): string {
  if (!detail) return 'no response body';
  try {
    const parsed = JSON.parse(detail) as { message?: string; errors?: unknown };
    if (parsed.message) {
      const extra = parsed.errors ? ` ${JSON.stringify(parsed.errors)}` : '';
      return `${parsed.message}${extra}`.slice(0, 300);
    }
  } catch {
    /* not JSON */
  }
  return detail.slice(0, 300);
}

/** Shorten `/repos/owner/name/git/trees` → `git/trees` for readable errors. */
function shortGitPath(path: string): string {
  return path.replace(/^\/repos\/[^/]+\/[^/]+\//, '').replace(/^\//, '') || path;
}
