/**
 * The AI interview loop — the platform's critical feature. The system runs a
 * structured, phased interview (A–E) until requirement completeness crosses a
 * threshold, then summarizes and waits for explicit user confirmation before
 * any design work begins.
 */

/** The five interview phases, matching the spec (A→E). */
export enum InterviewPhase {
  /** A — main goal & users. */
  Understanding = 'understanding',
  /** B — how the system works, approvals. */
  BusinessLogic = 'business_logic',
  /** C — payments, notifications, reports. */
  Features = 'features',
  /** D — expected users, MVP vs enterprise. */
  Scale = 'scale',
  /** E — SQL/NoSQL, monolith/microservices. */
  Technical = 'technical',
}

export const INTERVIEW_PHASE_ORDER: readonly InterviewPhase[] = [
  InterviewPhase.Understanding,
  InterviewPhase.BusinessLogic,
  InterviewPhase.Features,
  InterviewPhase.Scale,
  InterviewPhase.Technical,
] as const;

/** Requirement completeness required before the interview can be confirmed. */
export const COMPLETENESS_THRESHOLD = 0.9;

export type InterviewStatus =
  /** Still asking questions. */
  | 'collecting'
  /** Threshold reached; summary produced; waiting for user confirmation. */
  | 'awaiting_confirmation'
  /** User confirmed; requirements are locked and the pipeline may proceed. */
  | 'confirmed';

export interface InterviewQuestion {
  id: string;
  phase: InterviewPhase;
  prompt: string;
  /**
   * Optional preset choices the user can tap instead of typing. The client still
   * lets them add free-text detail; the submitted answer is the picks (joined)
   * plus any extra text.
   */
  options?: string[];
  /** When true the choices are multi-select (checkboxes); else single-select. */
  multiple?: boolean;
}

export interface InterviewExchange {
  question: InterviewQuestion;
  answer: string;
}

/** The Product Analyst's structured read of a raw idea (Intent Analysis stage). */
export interface IntentAnalysis {
  summary: string;
  domain: string;
  primaryUsers: string[];
  coreCapabilities: string[];
  openQuestions: string[];
}

/**
 * A lightweight requirements preview produced when the interview reaches the
 * confirmation gate. The full, formal Requirement Document is generated by the
 * Requirement Engineer in a later stage.
 */
export interface RequirementsSummary {
  goal: string;
  users: string[];
  features: string[];
  businessRules: string[];
  constraints: string[];
  assumptions: string[];
}

/**
 * A lightweight row for the "my projects" list — one per interview session the
 * signed-in user owns. The heavy artifacts are fetched on demand when opened.
 */
export interface ProjectSummary {
  sessionId: string;
  idea: string;
  /** Optional user-set display name; falls back to `idea` when absent. */
  title?: string;
  status: InterviewStatus;
  /** 0..1 requirement completeness (drives a small progress indicator). */
  completeness: number;
  /** ISO timestamp of the last change, for "most recently worked on" ordering. */
  updatedAt: string;
}

/** The full interview state returned to clients. */
export interface InterviewState {
  sessionId: string;
  status: InterviewStatus;
  /** Current phase being asked about, or null once complete. */
  phase: InterviewPhase | null;
  /** 0..1 requirement completeness. */
  completeness: number;
  intent: IntentAnalysis | null;
  history: InterviewExchange[];
  /** The question awaiting an answer, or null at the gate / when confirmed. */
  currentQuestion: InterviewQuestion | null;
  /** Present once the gate is reached. */
  summary: RequirementsSummary | null;
}
