/**
 * Deterministic **code scaffolding** — turns the confirmed design artifacts into
 * a runnable NestJS + Prisma backend starter. Pure and runtime-free (mirrors the
 * OpenAPI / structure / cost-estimate builders): no LLM, stable across runs, and
 * fully unit-testable offline.
 *
 * Mapping:
 *   - Database Design entities/relations → `prisma/schema.prisma` models.
 *   - API Design modules/endpoints       → NestJS modules, controllers, services,
 *                                           and class-validator DTOs.
 *   - System Design / idea               → root project files + README.
 *
 * Correctness over richness: the output always compiles and `prisma validate`s.
 * Foreign keys are emitted as scalar fields (documented via a comment) rather
 * than Prisma relations, so the schema is guaranteed valid regardless of how the
 * design names things; service methods are typed stubs that throw "Not
 * implemented", leaving the business logic to the developer.
 */

import type { SystemDesign } from './system-design';
import type { DatabaseDesign, Entity, EntityColumn } from './database-design';
import type { ApiDesign, ApiModule } from './api-design';
import {
  assignHandlers,
  camel,
  controllerBase,
  dedupe,
  fieldKind,
  httpMethod,
  kebab,
  mapName,
  oneLine,
  pascal,
  pascalMethod,
  prismaProvider,
  safePath,
  uniquifyNames,
  type Handler,
} from './scaffold.util';

/** A single generated file: a repo-relative path and its full text contents. */
export interface ScaffoldFile {
  path: string;
  content: string;
}

export interface ScaffoldInput {
  idea: string;
  systemDesign: SystemDesign;
  databaseDesign: DatabaseDesign;
  apiDesign: ApiDesign;
}

/**
 * What to generate: the NestJS backend, the Next.js frontend, or both as one
 * npm-workspaces monorepo (`apps/api` + `apps/web`).
 */
export type ScaffoldTarget = 'backend' | 'frontend' | 'fullstack';

export const SCAFFOLD_TARGETS: readonly ScaffoldTarget[] = [
  'backend',
  'frontend',
  'fullstack',
] as const;

/** The default when a caller doesn't say: the whole runnable app. */
export const DEFAULT_SCAFFOLD_TARGET: ScaffoldTarget = 'fullstack';

/** Manifest returned by the scaffold API (file list + count). */
export interface ScaffoldManifest {
  sessionId: string;
  generatedAt: string;
  target: ScaffoldTarget;
  /** Provider the deployment artifacts target (the cost recommendation by default). */
  provider: string;
  fileCount: number;
  files: ScaffoldFile[];
}

/** The port the generated frontend dev-serves on (the backend takes 3000). */
export const FRONTEND_DEV_PORT = 3001;

/** A user's GitHub connection state (no token material). */
export interface GithubConnectionStatus {
  /** Whether the scaffold OAuth app is configured on the server at all. */
  available: boolean;
  connected: boolean;
  login?: string;
}

/** Result of pushing the scaffold to a new GitHub repository. */
export interface GithubPushResult {
  /** Browser URL of the created repository. */
  htmlUrl: string;
  /** `owner/name` of the created repository. */
  repo: string;
  /** The branch the scaffold was committed to. */
  branch: string;
}

/**
 * Build the full backend scaffold as a flat, sorted list of files.
 */
export function buildBackendScaffold(input: ScaffoldInput): ScaffoldFile[] {
  const files: ScaffoldFile[] = [];

  // Names that normalize to the same identifier would collide into duplicate
  // files / duplicate class imports / duplicate Prisma models (a non-compiling
  // project). Make them unique up front so the output always builds.
  const entities = uniquifyNames(input.databaseDesign.entities, (e) =>
    pascal(e.name),
  );
  const modules = uniquifyNames(input.apiDesign.modules, (m) => kebab(m.name));

  files.push(...rootFiles(input));
  files.push({
    path: 'prisma/schema.prisma',
    content: renderPrismaSchema({ ...input.databaseDesign, entities }),
  });
  files.push(...frameworkFiles({ ...input.apiDesign, modules }));

  for (const mod of modules) {
    files.push(...moduleFiles(mod));
  }

  // Stable order so output is deterministic (and diffs are clean).
  return files.sort((a, b) => a.path.localeCompare(b.path));
}

// ── Prisma schema ────────────────────────────────────────────────────────────

function renderPrismaSchema(db: DatabaseDesign): string {
  const provider = prismaProvider(db.databaseType);
  const header = [
    '// Generated by Archivato — review before running `prisma migrate dev`.',
    '',
    'generator client {',
    '  provider = "prisma-client-js"',
    '}',
    '',
    'datasource db {',
    `  provider = "${provider}"`,
    '  url      = env("DATABASE_URL")',
    '}',
    '',
  ].join('\n');

  const models = db.entities.map((e) => renderModel(e)).join('\n\n');
  return `${header}\n${models}\n`;
}

function renderModel(entity: Entity): string {
  const modelName = pascal(entity.name);
  const lines: string[] = [`model ${modelName} {`];

  const hasPk = entity.columns.some((c) => c.primaryKey);
  // Prisma requires exactly one @id. If the design flags no primary key but an
  // `id` column exists, promote THAT column to the id (synthesizing a second
  // `id` would produce a duplicate field and fail `prisma validate`); only
  // synthesize when there is no `id` column at all.
  const idColIndex = entity.columns.findIndex((c) => camel(c.name) === 'id');
  const synthesizeId = !hasPk && idColIndex === -1;
  if (synthesizeId) {
    lines.push('  id String @id @default(uuid())');
  }

  entity.columns.forEach((col, i) => {
    const forcePrimary = !hasPk && !synthesizeId && i === idColIndex;
    lines.push('  ' + renderField(col, forcePrimary));
  });

  lines.push(`\n  @@map("${mapName(entity.name)}")`);
  lines.push('}');
  return lines.join('\n');
}

function renderField(col: EntityColumn, forcePrimary = false): string {
  const field = camel(col.name);
  const type = prismaType(col.type);
  const optional = col.nullable ? '?' : '';
  const attrs: string[] = [];

  const isPrimary = col.primaryKey || forcePrimary;
  if (isPrimary) {
    attrs.push('@id');
    if (type === 'String') attrs.push('@default(uuid())');
    else if (type === 'Int') attrs.push('@default(autoincrement())');
  }
  if (col.unique && !isPrimary) attrs.push('@unique');
  if (field !== col.name) attrs.push(`@map("${mapName(col.name)}")`);

  // A promoted `id` can't be optional (an @id field must be required).
  const suffix = isPrimary ? '' : optional;
  let line = `${field} ${type}${suffix}`;
  if (attrs.length) line += ' ' + attrs.join(' ');
  if (col.references) {
    line += ` // FK → ${col.references.entity}.${col.references.column}`;
  }
  return line;
}

function prismaType(raw: string): string {
  const t = (raw || '').toLowerCase();
  if (/(^| )(int|integer|serial|bigint|smallint)/.test(t)) return 'Int';
  if (/(decimal|numeric|float|double|real|money)/.test(t)) return 'Decimal';
  if (/(bool)/.test(t)) return 'Boolean';
  if (/(timestamp|datetime|^date$|^date )/.test(t)) return 'DateTime';
  if (/(json)/.test(t)) return 'Json';
  // uuid, string, text, varchar, char, enum, and anything unknown → String.
  return 'String';
}

// ── NestJS module files ──────────────────────────────────────────────────────

function moduleFiles(mod: ApiModule): ScaffoldFile[] {
  const slug = kebab(mod.name);
  const cls = pascal(mod.name);
  const dir = `src/modules/${slug}`;

  // Assign a unique handler name to each endpoint up front so controller,
  // service, and DTOs all agree.
  const handlers = assignHandlers(mod.endpoints);

  const files: ScaffoldFile[] = [];
  const dtos = handlers.filter((h) => h.dtoName);

  files.push({
    path: `${dir}/${slug}.module.ts`,
    content: renderModuleFile(cls),
  });
  files.push({
    path: `${dir}/${slug}.controller.ts`,
    content: renderControllerFile(mod, cls, slug, handlers),
  });
  files.push({
    path: `${dir}/${slug}.service.ts`,
    content: renderServiceFile(cls, handlers),
  });
  for (const h of dtos) {
    files.push({
      path: `${dir}/dto/${kebab(h.dtoName as string)}.ts`,
      content: renderDtoFile(h),
    });
  }
  return files;
}

function renderModuleFile(cls: string): string {
  return [
    `import { Module } from '@nestjs/common';`,
    `import { ${cls}Controller } from './${kebab(cls)}.controller';`,
    `import { ${cls}Service } from './${kebab(cls)}.service';`,
    '',
    '@Module({',
    `  controllers: [${cls}Controller],`,
    `  providers: [${cls}Service],`,
    '})',
    `export class ${cls}Module {}`,
    '',
  ].join('\n');
}

function renderControllerFile(
  mod: ApiModule,
  cls: string,
  slug: string,
  handlers: Handler[],
): string {
  const base = controllerBase(mod.basePath, slug);
  const nestImports = new Set<string>(['Controller']);
  const dtoImports: string[] = [];
  const methods: string[] = [];

  for (const h of handlers) {
    const dec = pascalMethod(h.endpoint.method); // Get, Post, ...
    nestImports.add(dec);

    const args: string[] = [];
    for (const p of h.params) {
      nestImports.add('Param');
      args.push(`@Param('${p}') ${p}: string`);
    }
    if (h.dtoName) {
      nestImports.add('Body');
      args.push(`@Body() dto: ${h.dtoName}`);
      dtoImports.push(
        `import { ${h.dtoName} } from './dto/${kebab(h.dtoName)}';`,
      );
    }

    const callArgs = [...h.params, ...(h.dtoName ? ['dto'] : [])].join(', ');
    const pathArg = h.subPath ? `'${h.subPath}'` : '';
    methods.push(
      [
        // oneLine: a newline in a designed summary would end this comment and
        // leave the rest of it sitting in the class body as code.
        `  // ${oneLine(
          `${httpMethod(h.endpoint.method)} ${safePath(h.endpoint.path)} — ${h.endpoint.summary}`,
        )}`,
        `  @${dec}(${pathArg})`,
        `  ${h.name}(${args.join(', ')}): Promise<unknown> {`,
        `    return this.service.${h.name}(${callArgs});`,
        `  }`,
      ].join('\n'),
    );
  }

  return [
    `import { ${[...nestImports].sort().join(', ')} } from '@nestjs/common';`,
    ...dedupe(dtoImports),
    `import { ${cls}Service } from './${slug}.service';`,
    '',
    `@Controller('${base}')`,
    `export class ${cls}Controller {`,
    `  constructor(private readonly service: ${cls}Service) {}`,
    '',
    methods.join('\n\n'),
    `}`,
    '',
  ].join('\n');
}

function renderServiceFile(cls: string, handlers: Handler[]): string {
  const methods = handlers.map((h) => {
    const args: string[] = [
      ...h.params.map((p) => `${p}: string`),
      ...(h.dtoName ? [`dto: ${h.dtoName}`] : []),
    ];
    const dtoImport = h.dtoName
      ? `  // eslint-disable-next-line @typescript-eslint/no-unused-vars`
      : '';
    return [
      dtoImport,
      `  async ${h.name}(${args.join(', ')}): Promise<unknown> {`,
      `    // TODO: implement with this.prisma`,
      `    throw new Error('Not implemented: ${cls}.${h.name}');`,
      `  }`,
    ]
      .filter(Boolean)
      .join('\n');
  });

  const dtoImports = dedupe(
    handlers
      .filter((h) => h.dtoName)
      .map((h) => `import { ${h.dtoName} } from './dto/${kebab(h.dtoName as string)}';`),
  );

  return [
    `import { Injectable } from '@nestjs/common';`,
    `import { PrismaService } from '../../prisma/prisma.service';`,
    ...dtoImports,
    '',
    '@Injectable()',
    `export class ${cls}Service {`,
    `  constructor(private readonly prisma: PrismaService) {}`,
    '',
    methods.join('\n\n'),
    `}`,
    '',
  ].join('\n');
}

function renderDtoFile(h: Handler): string {
  const validators = new Set<string>();
  const fieldLines: string[] = [];

  for (const f of h.dtoFields) {
    const decs: string[] = [];
    if (!f.required) {
      validators.add('IsOptional');
      decs.push('  @IsOptional()');
    }
    const kind = fieldKind(f.type);
    validators.add(kind.validator);
    decs.push(`  @${kind.validator}()`);
    // `!`, not bare: a required field with no initializer fails TS's
    // strictPropertyInitialization (TS2564) and the project would not compile.
    // It's the same definite-assignment convention Nest DTOs use everywhere.
    const mark = f.required ? '!' : '?';
    fieldLines.push(`${decs.join('\n')}\n  ${camel(f.name)}${mark}: ${kind.ts};`);
  }

  const importLine = validators.size
    ? `import { ${[...validators].sort().join(', ')} } from 'class-validator';\n\n`
    : '';

  return `${importLine}export class ${h.dtoName} {\n${fieldLines.join('\n\n')}\n}\n`;
}

// ── Framework + root files ───────────────────────────────────────────────────

function frameworkFiles(api: ApiDesign): ScaffoldFile[] {
  const moduleImports = api.modules
    .map((m) => {
      const cls = pascal(m.name);
      return `import { ${cls}Module } from './modules/${kebab(m.name)}/${kebab(
        m.name,
      )}.module';`;
    })
    .join('\n');
  const moduleList = api.modules.map((m) => `${pascal(m.name)}Module`).join(', ');

  const appModule = [
    `import { Module } from '@nestjs/common';`,
    `import { PrismaModule } from './prisma/prisma.module';`,
    `import { HealthController } from './health.controller';`,
    moduleImports,
    '',
    '@Module({',
    `  imports: [PrismaModule${moduleList ? ', ' + moduleList : ''}],`,
    '  controllers: [HealthController],',
    '})',
    'export class AppModule {}',
    '',
  ].join('\n');

  // Every host wants a health check, and pointing one at a route that doesn't
  // exist (a 404) is how a perfectly good deploy gets marked unhealthy forever.
  const health = [
    `import { Controller, Get } from '@nestjs/common';`,
    '',
    `@Controller('health')`,
    'export class HealthController {',
    '  @Get()',
    '  check(): { status: string } {',
    `    return { status: 'ok' };`,
    '  }',
    '}',
    '',
  ].join('\n');

  const main = [
    `import { NestFactory } from '@nestjs/core';`,
    `import { ValidationPipe } from '@nestjs/common';`,
    `import { AppModule } from './app.module';`,
    '',
    'async function bootstrap() {',
    '  const app = await NestFactory.create(AppModule);',
    '  app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true }));',
    '  // The generated frontend runs on a different origin, so the browser needs',
    '  // this to call the API at all. Lock WEB_ORIGIN down in production.',
    '  app.enableCors({',
    `    origin: process.env.WEB_ORIGIN ?? 'http://localhost:${FRONTEND_DEV_PORT}',`,
    '    credentials: true,',
    '  });',
    `  app.setGlobalPrefix('api');`,
    '  await app.listen(process.env.PORT ? Number(process.env.PORT) : 3000);',
    '}',
    'bootstrap();',
    '',
  ].join('\n');

  const prismaService = [
    `import { Injectable, OnModuleInit } from '@nestjs/common';`,
    `import { PrismaClient } from '@prisma/client';`,
    '',
    '@Injectable()',
    'export class PrismaService extends PrismaClient implements OnModuleInit {',
    '  async onModuleInit(): Promise<void> {',
    '    await this.$connect();',
    '  }',
    '}',
    '',
  ].join('\n');

  const prismaModule = [
    `import { Global, Module } from '@nestjs/common';`,
    `import { PrismaService } from './prisma.service';`,
    '',
    '@Global()',
    '@Module({',
    '  providers: [PrismaService],',
    '  exports: [PrismaService],',
    '})',
    'export class PrismaModule {}',
    '',
  ].join('\n');

  return [
    { path: 'src/app.module.ts', content: appModule },
    { path: 'src/main.ts', content: main },
    { path: 'src/health.controller.ts', content: health },
    { path: 'src/prisma/prisma.service.ts', content: prismaService },
    { path: 'src/prisma/prisma.module.ts', content: prismaModule },
  ];
}

function rootFiles(input: ScaffoldInput): ScaffoldFile[] {
  const pkg = {
    name: 'generated-backend',
    version: '0.1.0',
    private: true,
    scripts: {
      build: 'nest build',
      start: 'nest start',
      'start:dev': 'nest start --watch',
      'start:prod': 'node dist/main.js',
      'prisma:generate': 'prisma generate',
      'prisma:migrate': 'prisma migrate dev',
    },
    dependencies: {
      '@nestjs/common': '^10.3.0',
      '@nestjs/core': '^10.3.0',
      '@nestjs/platform-express': '^10.3.0',
      '@prisma/client': '^5.22.0',
      'class-transformer': '^0.5.1',
      'class-validator': '^0.14.1',
      'reflect-metadata': '^0.2.1',
      rxjs: '^7.8.1',
    },
    devDependencies: {
      '@nestjs/cli': '^10.3.0',
      prisma: '^5.22.0',
      typescript: '^5.4.0',
    },
  };

  const tsconfig = {
    compilerOptions: {
      module: 'commonjs',
      target: 'ES2021',
      moduleResolution: 'node',
      experimentalDecorators: true,
      emitDecoratorMetadata: true,
      declaration: false,
      outDir: './dist',
      baseUrl: './',
      strict: true,
      skipLibCheck: true,
      esModuleInterop: true,
    },
  };

  return [
    { path: 'package.json', content: JSON.stringify(pkg, null, 2) + '\n' },
    { path: 'tsconfig.json', content: JSON.stringify(tsconfig, null, 2) + '\n' },
    {
      path: 'nest-cli.json',
      content:
        JSON.stringify(
          { collection: '@nestjs/schematics', sourceRoot: 'src' },
          null,
          2,
        ) + '\n',
    },
    {
      path: '.gitignore',
      content: ['node_modules/', 'dist/', '.env', ''].join('\n'),
    },
    {
      path: '.env.example',
      content: [
        '# Copy to .env and set your database connection string.',
        `DATABASE_URL="${exampleDbUrl(input.databaseDesign.databaseType)}"`,
        'PORT=3000',
        '# Origin allowed to call this API from a browser (the generated frontend).',
        `WEB_ORIGIN=http://localhost:${FRONTEND_DEV_PORT}`,
        '',
      ].join('\n'),
    },
    { path: 'README.md', content: renderReadme(input) },
  ];
}

function renderReadme(input: ScaffoldInput): string {
  const { idea, systemDesign, databaseDesign, apiDesign } = input;
  const entityList = databaseDesign.entities.map((e) => `- \`${e.name}\``).join('\n');
  const moduleList = apiDesign.modules
    .map((m) => `- **${m.name}** (${m.endpoints.length} endpoints)`)
    .join('\n');

  return [
    '# Generated Backend',
    '',
    '> Scaffolded by **Archivato AI Builder** from your system design. This is a',
    "> starting point — service methods are stubs that throw \"Not implemented\".",
    '',
    '## The idea',
    '',
    idea,
    '',
    `**Architecture:** ${systemDesign.architecture}`,
    '',
    '## Getting started',
    '',
    '```bash',
    'npm install',
    'cp .env.example .env      # set DATABASE_URL',
    'npm run prisma:migrate    # create the schema',
    'npm run start:dev         # http://localhost:3000/api',
    '```',
    '',
    '## Data model',
    '',
    entityList || '_No entities._',
    '',
    '## API modules',
    '',
    moduleList || '_No modules._',
    '',
    '## Next steps',
    '',
    '1. Review `prisma/schema.prisma` (foreign keys are scalar fields + comments;',
    '   convert them to Prisma relations where you want referential integrity).',
    '2. Implement each service method (they currently throw "Not implemented").',
    '3. Add authentication, validation, and tests.',
    '',
  ].join('\n');
}

function exampleDbUrl(databaseType: string): string {
  switch (prismaProvider(databaseType)) {
    case 'mysql':
      return 'mysql://user:password@localhost:3306/app';
    case 'sqlite':
      return 'file:./dev.db';
    case 'sqlserver':
      return 'sqlserver://localhost:1433;database=app;user=sa;password=Password1;';
    case 'mongodb':
      return 'mongodb://localhost:27017/app';
    default:
      return 'postgresql://user:password@localhost:5432/app?schema=public';
  }
}

// Path / casing helpers live in `scaffold.util.ts` — shared with the frontend
// builder so both derive identical names from the same design.
