/**
 * Deterministic **code scaffolding** — turns the confirmed design artifacts into
 * a runnable NestJS + Prisma backend starter. Pure and runtime-free (mirrors the
 * OpenAPI / structure / cost-estimate builders): no LLM, stable across runs, and
 * fully unit-testable offline.
 *
 * Mapping:
 *   - Database Design entities/relations → `prisma/schema.prisma` models.
 *   - API Design modules/endpoints       → NestJS modules, controllers, services,
 *                                           and class-validator DTOs.
 *   - System Design / idea               → root project files + README.
 *
 * Correctness over richness: the output always compiles and `prisma validate`s.
 * Foreign keys are emitted as scalar fields (documented via a comment) rather
 * than Prisma relations, so the schema is guaranteed valid regardless of how the
 * design names things; service methods are typed stubs that throw "Not
 * implemented", leaving the business logic to the developer.
 */

import type { SystemDesign } from './system-design';
import type { DatabaseDesign, Entity, EntityColumn } from './database-design';
import type { ApiDesign, ApiEndpoint, ApiModule, SchemaField } from './api-design';

/** A single generated file: a repo-relative path and its full text contents. */
export interface ScaffoldFile {
  path: string;
  content: string;
}

export interface ScaffoldInput {
  idea: string;
  systemDesign: SystemDesign;
  databaseDesign: DatabaseDesign;
  apiDesign: ApiDesign;
}

/** Manifest returned by the scaffold API (file list + count). */
export interface ScaffoldManifest {
  sessionId: string;
  generatedAt: string;
  fileCount: number;
  files: ScaffoldFile[];
}

/** A user's GitHub connection state (no token material). */
export interface GithubConnectionStatus {
  /** Whether the scaffold OAuth app is configured on the server at all. */
  available: boolean;
  connected: boolean;
  login?: string;
}

/** Result of pushing the scaffold to a new GitHub repository. */
export interface GithubPushResult {
  /** Browser URL of the created repository. */
  htmlUrl: string;
  /** `owner/name` of the created repository. */
  repo: string;
  /** The branch the scaffold was committed to. */
  branch: string;
}

/** Fields the server manages — never accepted in a request DTO. */
const SERVER_MANAGED = new Set([
  'id',
  'created_at',
  'updated_at',
  'createdat',
  'updatedat',
  'password_hash',
  'passwordhash',
]);

/**
 * Build the full backend scaffold as a flat, sorted list of files.
 */
export function buildBackendScaffold(input: ScaffoldInput): ScaffoldFile[] {
  const files: ScaffoldFile[] = [];

  // Names that normalize to the same identifier would collide into duplicate
  // files / duplicate class imports / duplicate Prisma models (a non-compiling
  // project). Make them unique up front so the output always builds.
  const entities = uniquifyNames(input.databaseDesign.entities, (e) =>
    pascal(e.name),
  );
  const modules = uniquifyNames(input.apiDesign.modules, (m) => kebab(m.name));

  files.push(...rootFiles(input));
  files.push({
    path: 'prisma/schema.prisma',
    content: renderPrismaSchema({ ...input.databaseDesign, entities }),
  });
  files.push(...frameworkFiles({ ...input.apiDesign, modules }));

  for (const mod of modules) {
    files.push(...moduleFiles(mod));
  }

  // Stable order so output is deterministic (and diffs are clean).
  return files.sort((a, b) => a.path.localeCompare(b.path));
}

/**
 * Ensure the derived key (via `keyOf`) is unique across items by suffixing the
 * `name` of later collisions (" 2", " 3", …). Works for any item with a `name`.
 */
function uniquifyNames<T extends { name: string }>(
  items: T[],
  keyOf: (item: T) => string,
): T[] {
  const counts = new Map<string, number>();
  return items.map((item) => {
    const key = keyOf(item).toLowerCase();
    const seen = counts.get(key) ?? 0;
    counts.set(key, seen + 1);
    return seen === 0 ? item : { ...item, name: `${item.name} ${seen + 1}` };
  });
}

// ── Prisma schema ────────────────────────────────────────────────────────────

function renderPrismaSchema(db: DatabaseDesign): string {
  const provider = prismaProvider(db.databaseType);
  const header = [
    '// Generated by Archivato — review before running `prisma migrate dev`.',
    '',
    'generator client {',
    '  provider = "prisma-client-js"',
    '}',
    '',
    'datasource db {',
    `  provider = "${provider}"`,
    '  url      = env("DATABASE_URL")',
    '}',
    '',
  ].join('\n');

  const models = db.entities.map((e) => renderModel(e)).join('\n\n');
  return `${header}\n${models}\n`;
}

function renderModel(entity: Entity): string {
  const modelName = pascal(entity.name);
  const lines: string[] = [`model ${modelName} {`];

  const hasPk = entity.columns.some((c) => c.primaryKey);
  // Prisma requires exactly one @id. If the design flags no primary key but an
  // `id` column exists, promote THAT column to the id (synthesizing a second
  // `id` would produce a duplicate field and fail `prisma validate`); only
  // synthesize when there is no `id` column at all.
  const idColIndex = entity.columns.findIndex((c) => camel(c.name) === 'id');
  const synthesizeId = !hasPk && idColIndex === -1;
  if (synthesizeId) {
    lines.push('  id String @id @default(uuid())');
  }

  entity.columns.forEach((col, i) => {
    const forcePrimary = !hasPk && !synthesizeId && i === idColIndex;
    lines.push('  ' + renderField(col, forcePrimary));
  });

  lines.push(`\n  @@map("${entity.name}")`);
  lines.push('}');
  return lines.join('\n');
}

function renderField(col: EntityColumn, forcePrimary = false): string {
  const field = camel(col.name);
  const type = prismaType(col.type);
  const optional = col.nullable ? '?' : '';
  const attrs: string[] = [];

  const isPrimary = col.primaryKey || forcePrimary;
  if (isPrimary) {
    attrs.push('@id');
    if (type === 'String') attrs.push('@default(uuid())');
    else if (type === 'Int') attrs.push('@default(autoincrement())');
  }
  if (col.unique && !isPrimary) attrs.push('@unique');
  if (field !== col.name) attrs.push(`@map("${col.name}")`);

  // A promoted `id` can't be optional (an @id field must be required).
  const suffix = isPrimary ? '' : optional;
  let line = `${field} ${type}${suffix}`;
  if (attrs.length) line += ' ' + attrs.join(' ');
  if (col.references) {
    line += ` // FK → ${col.references.entity}.${col.references.column}`;
  }
  return line;
}

function prismaProvider(databaseType: string): string {
  const t = (databaseType || '').toLowerCase();
  if (t.includes('mysql') || t.includes('maria')) return 'mysql';
  if (t.includes('sqlite')) return 'sqlite';
  if (t.includes('sqlserver') || t.includes('mssql')) return 'sqlserver';
  if (t.includes('mongo')) return 'mongodb';
  return 'postgresql';
}

function prismaType(raw: string): string {
  const t = (raw || '').toLowerCase();
  if (/(^| )(int|integer|serial|bigint|smallint)/.test(t)) return 'Int';
  if (/(decimal|numeric|float|double|real|money)/.test(t)) return 'Decimal';
  if (/(bool)/.test(t)) return 'Boolean';
  if (/(timestamp|datetime|^date$|^date )/.test(t)) return 'DateTime';
  if (/(json)/.test(t)) return 'Json';
  // uuid, string, text, varchar, char, enum, and anything unknown → String.
  return 'String';
}

// ── NestJS module files ──────────────────────────────────────────────────────

function moduleFiles(mod: ApiModule): ScaffoldFile[] {
  const slug = kebab(mod.name);
  const cls = pascal(mod.name);
  const dir = `src/modules/${slug}`;

  // Assign a unique handler name to each endpoint up front so controller,
  // service, and DTOs all agree.
  const handlers = assignHandlers(mod.endpoints);

  const files: ScaffoldFile[] = [];
  const dtos = handlers.filter((h) => h.dtoName);

  files.push({
    path: `${dir}/${slug}.module.ts`,
    content: renderModuleFile(cls),
  });
  files.push({
    path: `${dir}/${slug}.controller.ts`,
    content: renderControllerFile(mod, cls, slug, handlers),
  });
  files.push({
    path: `${dir}/${slug}.service.ts`,
    content: renderServiceFile(cls, handlers),
  });
  for (const h of dtos) {
    files.push({
      path: `${dir}/dto/${kebab(h.dtoName as string)}.ts`,
      content: renderDtoFile(h),
    });
  }
  return files;
}

interface Handler {
  endpoint: ApiEndpoint;
  name: string;
  /** Path relative to the controller base, e.g. ':id' or '' for the root. */
  subPath: string;
  /** Path params in order, e.g. ['id']. */
  params: string[];
  /** DTO class name when the endpoint takes a request body, else null. */
  dtoName: string | null;
  dtoFields: SchemaField[];
}

function assignHandlers(endpoints: ApiEndpoint[]): Handler[] {
  const used = new Set<string>();
  return endpoints.map((endpoint) => {
    const subPath = relativePath(endpoint.path);
    const params = [...subPath.matchAll(/:(\w+)/g)].map((m) => m[1]);

    let name = baseHandlerName(endpoint.method, params.length > 0);
    let unique = name;
    let n = 2;
    while (used.has(unique)) unique = `${name}${n++}`;
    used.add(unique);
    name = unique;

    const takesBody =
      ['POST', 'PUT', 'PATCH'].includes(endpoint.method) &&
      dtoFields(endpoint.requestSchema).length > 0;

    return {
      endpoint,
      name,
      subPath,
      params,
      dtoName: takesBody ? `${pascal(name)}Dto` : null,
      dtoFields: takesBody ? dtoFields(endpoint.requestSchema) : [],
    };
  });
}

function dtoFields(schema: SchemaField[]): SchemaField[] {
  return schema.filter((f) => !SERVER_MANAGED.has(f.name.toLowerCase()));
}

function baseHandlerName(method: string, hasId: boolean): string {
  switch (method) {
    case 'GET':
      return hasId ? 'findOne' : 'findAll';
    case 'POST':
      return 'create';
    case 'PUT':
    case 'PATCH':
      return 'update';
    case 'DELETE':
      return 'remove';
    default:
      return 'handle';
  }
}

function renderModuleFile(cls: string): string {
  return [
    `import { Module } from '@nestjs/common';`,
    `import { ${cls}Controller } from './${kebabFromClass(cls)}.controller';`,
    `import { ${cls}Service } from './${kebabFromClass(cls)}.service';`,
    '',
    '@Module({',
    `  controllers: [${cls}Controller],`,
    `  providers: [${cls}Service],`,
    '})',
    `export class ${cls}Module {}`,
    '',
  ].join('\n');
}

function renderControllerFile(
  mod: ApiModule,
  cls: string,
  slug: string,
  handlers: Handler[],
): string {
  const base = controllerBase(mod.basePath, slug);
  const nestImports = new Set<string>(['Controller']);
  const dtoImports: string[] = [];
  const methods: string[] = [];

  for (const h of handlers) {
    const dec = pascalMethod(h.endpoint.method); // Get, Post, ...
    nestImports.add(dec);

    const args: string[] = [];
    for (const p of h.params) {
      nestImports.add('Param');
      args.push(`@Param('${p}') ${p}: string`);
    }
    if (h.dtoName) {
      nestImports.add('Body');
      args.push(`@Body() dto: ${h.dtoName}`);
      dtoImports.push(
        `import { ${h.dtoName} } from './dto/${kebab(h.dtoName)}';`,
      );
    }

    const callArgs = [...h.params, ...(h.dtoName ? ['dto'] : [])].join(', ');
    const pathArg = h.subPath ? `'${h.subPath}'` : '';
    methods.push(
      [
        `  // ${h.endpoint.method} ${h.endpoint.path} — ${h.endpoint.summary}`,
        `  @${dec}(${pathArg})`,
        `  ${h.name}(${args.join(', ')}): Promise<unknown> {`,
        `    return this.service.${h.name}(${callArgs});`,
        `  }`,
      ].join('\n'),
    );
  }

  return [
    `import { ${[...nestImports].sort().join(', ')} } from '@nestjs/common';`,
    ...dedupe(dtoImports),
    `import { ${cls}Service } from './${slug}.service';`,
    '',
    `@Controller('${base}')`,
    `export class ${cls}Controller {`,
    `  constructor(private readonly service: ${cls}Service) {}`,
    '',
    methods.join('\n\n'),
    `}`,
    '',
  ].join('\n');
}

function renderServiceFile(cls: string, handlers: Handler[]): string {
  const methods = handlers.map((h) => {
    const args: string[] = [
      ...h.params.map((p) => `${p}: string`),
      ...(h.dtoName ? [`dto: ${h.dtoName}`] : []),
    ];
    const dtoImport = h.dtoName
      ? `  // eslint-disable-next-line @typescript-eslint/no-unused-vars`
      : '';
    return [
      dtoImport,
      `  async ${h.name}(${args.join(', ')}): Promise<unknown> {`,
      `    // TODO: implement with this.prisma`,
      `    throw new Error('Not implemented: ${cls}.${h.name}');`,
      `  }`,
    ]
      .filter(Boolean)
      .join('\n');
  });

  const dtoImports = dedupe(
    handlers
      .filter((h) => h.dtoName)
      .map((h) => `import { ${h.dtoName} } from './dto/${kebab(h.dtoName as string)}';`),
  );

  return [
    `import { Injectable } from '@nestjs/common';`,
    `import { PrismaService } from '../../prisma/prisma.service';`,
    ...dtoImports,
    '',
    '@Injectable()',
    `export class ${cls}Service {`,
    `  constructor(private readonly prisma: PrismaService) {}`,
    '',
    methods.join('\n\n'),
    `}`,
    '',
  ].join('\n');
}

function renderDtoFile(h: Handler): string {
  const validators = new Set<string>();
  const fieldLines: string[] = [];

  for (const f of h.dtoFields) {
    const decs: string[] = [];
    if (!f.required) {
      validators.add('IsOptional');
      decs.push('  @IsOptional()');
    }
    const v = validatorFor(f.type);
    validators.add(v.name);
    decs.push(`  @${v.name}()`);
    const opt = f.required ? '' : '?';
    fieldLines.push(`${decs.join('\n')}\n  ${camel(f.name)}${opt}: ${v.ts};`);
  }

  const importLine = validators.size
    ? `import { ${[...validators].sort().join(', ')} } from 'class-validator';\n\n`
    : '';

  return `${importLine}export class ${h.dtoName} {\n${fieldLines.join('\n\n')}\n}\n`;
}

function validatorFor(rawType: string): { name: string; ts: string } {
  const t = (rawType || '').toLowerCase();
  if (/(^| )(int|integer|serial|bigint|smallint)/.test(t))
    return { name: 'IsInt', ts: 'number' };
  if (/(decimal|numeric|float|double|real|money)/.test(t))
    return { name: 'IsNumber', ts: 'number' };
  if (/(bool)/.test(t)) return { name: 'IsBoolean', ts: 'boolean' };
  if (/(timestamp|datetime|^date$|^date )/.test(t))
    return { name: 'IsDateString', ts: 'string' };
  if (/(json)/.test(t)) return { name: 'IsObject', ts: 'Record<string, unknown>' };
  return { name: 'IsString', ts: 'string' };
}

// ── Framework + root files ───────────────────────────────────────────────────

function frameworkFiles(api: ApiDesign): ScaffoldFile[] {
  const moduleImports = api.modules
    .map((m) => {
      const cls = pascal(m.name);
      return `import { ${cls}Module } from './modules/${kebab(m.name)}/${kebab(
        m.name,
      )}.module';`;
    })
    .join('\n');
  const moduleList = api.modules.map((m) => `${pascal(m.name)}Module`).join(', ');

  const appModule = [
    `import { Module } from '@nestjs/common';`,
    `import { PrismaModule } from './prisma/prisma.module';`,
    moduleImports,
    '',
    '@Module({',
    `  imports: [PrismaModule${moduleList ? ', ' + moduleList : ''}],`,
    '})',
    'export class AppModule {}',
    '',
  ].join('\n');

  const main = [
    `import { NestFactory } from '@nestjs/core';`,
    `import { ValidationPipe } from '@nestjs/common';`,
    `import { AppModule } from './app.module';`,
    '',
    'async function bootstrap() {',
    '  const app = await NestFactory.create(AppModule);',
    '  app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true }));',
    `  app.setGlobalPrefix('api');`,
    '  await app.listen(process.env.PORT ? Number(process.env.PORT) : 3000);',
    '}',
    'bootstrap();',
    '',
  ].join('\n');

  const prismaService = [
    `import { Injectable, OnModuleInit } from '@nestjs/common';`,
    `import { PrismaClient } from '@prisma/client';`,
    '',
    '@Injectable()',
    'export class PrismaService extends PrismaClient implements OnModuleInit {',
    '  async onModuleInit(): Promise<void> {',
    '    await this.$connect();',
    '  }',
    '}',
    '',
  ].join('\n');

  const prismaModule = [
    `import { Global, Module } from '@nestjs/common';`,
    `import { PrismaService } from './prisma.service';`,
    '',
    '@Global()',
    '@Module({',
    '  providers: [PrismaService],',
    '  exports: [PrismaService],',
    '})',
    'export class PrismaModule {}',
    '',
  ].join('\n');

  return [
    { path: 'src/app.module.ts', content: appModule },
    { path: 'src/main.ts', content: main },
    { path: 'src/prisma/prisma.service.ts', content: prismaService },
    { path: 'src/prisma/prisma.module.ts', content: prismaModule },
  ];
}

function rootFiles(input: ScaffoldInput): ScaffoldFile[] {
  const pkg = {
    name: 'generated-backend',
    version: '0.1.0',
    private: true,
    scripts: {
      build: 'nest build',
      start: 'nest start',
      'start:dev': 'nest start --watch',
      'start:prod': 'node dist/main.js',
      'prisma:generate': 'prisma generate',
      'prisma:migrate': 'prisma migrate dev',
    },
    dependencies: {
      '@nestjs/common': '^10.3.0',
      '@nestjs/core': '^10.3.0',
      '@nestjs/platform-express': '^10.3.0',
      '@prisma/client': '^5.22.0',
      'class-transformer': '^0.5.1',
      'class-validator': '^0.14.1',
      'reflect-metadata': '^0.2.1',
      rxjs: '^7.8.1',
    },
    devDependencies: {
      '@nestjs/cli': '^10.3.0',
      prisma: '^5.22.0',
      typescript: '^5.4.0',
    },
  };

  const tsconfig = {
    compilerOptions: {
      module: 'commonjs',
      target: 'ES2021',
      moduleResolution: 'node',
      experimentalDecorators: true,
      emitDecoratorMetadata: true,
      declaration: false,
      outDir: './dist',
      baseUrl: './',
      strict: true,
      skipLibCheck: true,
      esModuleInterop: true,
    },
  };

  return [
    { path: 'package.json', content: JSON.stringify(pkg, null, 2) + '\n' },
    { path: 'tsconfig.json', content: JSON.stringify(tsconfig, null, 2) + '\n' },
    {
      path: 'nest-cli.json',
      content:
        JSON.stringify(
          { collection: '@nestjs/schematics', sourceRoot: 'src' },
          null,
          2,
        ) + '\n',
    },
    {
      path: '.gitignore',
      content: ['node_modules/', 'dist/', '.env', ''].join('\n'),
    },
    {
      path: '.env.example',
      content: [
        '# Copy to .env and set your database connection string.',
        `DATABASE_URL="${exampleDbUrl(input.databaseDesign.databaseType)}"`,
        'PORT=3000',
        '',
      ].join('\n'),
    },
    { path: 'README.md', content: renderReadme(input) },
  ];
}

function renderReadme(input: ScaffoldInput): string {
  const { idea, systemDesign, databaseDesign, apiDesign } = input;
  const entityList = databaseDesign.entities.map((e) => `- \`${e.name}\``).join('\n');
  const moduleList = apiDesign.modules
    .map((m) => `- **${m.name}** (${m.endpoints.length} endpoints)`)
    .join('\n');

  return [
    '# Generated Backend',
    '',
    '> Scaffolded by **Archivato AI Builder** from your system design. This is a',
    "> starting point — service methods are stubs that throw \"Not implemented\".",
    '',
    '## The idea',
    '',
    idea,
    '',
    `**Architecture:** ${systemDesign.architecture}`,
    '',
    '## Getting started',
    '',
    '```bash',
    'npm install',
    'cp .env.example .env      # set DATABASE_URL',
    'npm run prisma:migrate    # create the schema',
    'npm run start:dev         # http://localhost:3000/api',
    '```',
    '',
    '## Data model',
    '',
    entityList || '_No entities._',
    '',
    '## API modules',
    '',
    moduleList || '_No modules._',
    '',
    '## Next steps',
    '',
    '1. Review `prisma/schema.prisma` (foreign keys are scalar fields + comments;',
    '   convert them to Prisma relations where you want referential integrity).',
    '2. Implement each service method (they currently throw "Not implemented").',
    '3. Add authentication, validation, and tests.',
    '',
  ].join('\n');
}

function exampleDbUrl(databaseType: string): string {
  switch (prismaProvider(databaseType)) {
    case 'mysql':
      return 'mysql://user:password@localhost:3306/app';
    case 'sqlite':
      return 'file:./dev.db';
    case 'sqlserver':
      return 'sqlserver://localhost:1433;database=app;user=sa;password=Password1;';
    case 'mongodb':
      return 'mongodb://localhost:27017/app';
    default:
      return 'postgresql://user:password@localhost:5432/app?schema=public';
  }
}

// ── Path / casing helpers ────────────────────────────────────────────────────

/** Strip the leading `/api` and surrounding slashes from a designed path. */
function stripApi(p: string): string {
  return (p || '').replace(/^\/?api/i, '').replace(/^\/+|\/+$/g, '');
}

/** The controller base path (no leading slash), e.g. `/api/users` → `users`. */
function controllerBase(basePath: string, slug: string): string {
  const base = stripApi(basePath);
  return base || slug;
}

/**
 * An endpoint's path relative to its module base — the arg to `@Get(...)`.
 * `/api/users/:id` (base `/api/users`) → `:id`; `/api/users` → ``.
 */
function relativePath(endpointPath: string): string {
  const segments = stripApi(endpointPath).split('/').filter(Boolean);
  // Drop the first segment (the resource, already the controller base) and keep
  // the remainder (ids / sub-resources). This keeps nested paths intact.
  return segments.slice(1).join('/');
}

function words(s: string): string[] {
  return (s || '')
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .filter(Boolean);
}

function pascal(s: string): string {
  const w = words(s);
  if (w.length === 0) return 'Resource';
  return w.map((x) => x[0].toUpperCase() + x.slice(1).toLowerCase()).join('');
}

function camel(s: string): string {
  const p = pascal(s);
  return p ? p[0].toLowerCase() + p.slice(1) : p;
}

function kebab(s: string): string {
  const w = words(s);
  return w.length ? w.map((x) => x.toLowerCase()).join('-') : 'resource';
}

function kebabFromClass(cls: string): string {
  return kebab(cls);
}

function pascalMethod(method: string): string {
  return method.charAt(0).toUpperCase() + method.slice(1).toLowerCase();
}

function dedupe(arr: string[]): string[] {
  return [...new Set(arr)];
}
