/**
 * Builds a runnable PostgreSQL DDL script (`schema.sql`) from a Database Design.
 * Pure and dependency-free — every table is emitted with quoted identifiers, a
 * primary key, and its columns; foreign keys are added afterwards as `ALTER
 * TABLE … ADD CONSTRAINT` statements so the script runs regardless of table
 * order (no forward-reference problems). The output always parses as valid
 * PostgreSQL for a well-formed design.
 */
import type { ColumnType, DatabaseDesign, Entity } from './database-design';

export function buildSqlDdl(design: DatabaseDesign): string {
  const dialect = /mysql/i.test(design.databaseType)
    ? design.databaseType
    : 'PostgreSQL';
  const lines: string[] = [
    `-- Database schema generated by Archivato AI Builder`,
    `-- Target: ${dialect}`,
    '',
  ];

  for (const entity of design.entities) {
    lines.push(createTable(entity), '');
  }

  const constraints = foreignKeys(design);
  if (constraints.length) {
    lines.push('-- Foreign keys', ...constraints, '');
  }

  return lines.join('\n');
}

function createTable(entity: Entity): string {
  const cols = entity.columns.map((c) => '  ' + columnDef(c));
  const pk = entity.columns.filter((c) => c.primaryKey).map((c) => c.name);
  const body = [...cols];
  if (pk.length) {
    body.push(`  PRIMARY KEY (${pk.map(quote).join(', ')})`);
  }
  const comment = entity.description
    ? `-- ${entity.description}\n`
    : '';
  return `${comment}CREATE TABLE ${quote(entity.name)} (\n${body.join(',\n')}\n);`;
}

function columnDef(col: {
  name: string;
  type: ColumnType;
  nullable: boolean;
  unique?: boolean;
}): string {
  const parts = [quote(col.name), sqlType(col.type)];
  if (!col.nullable) parts.push('NOT NULL');
  if (col.unique) parts.push('UNIQUE');
  return parts.join(' ');
}

/** One `ALTER TABLE … ADD CONSTRAINT … FOREIGN KEY` per referencing column. */
function foreignKeys(design: DatabaseDesign): string[] {
  const out: string[] = [];
  for (const entity of design.entities) {
    for (const col of entity.columns) {
      if (!col.references) continue;
      const name = `${entity.name}_${col.name}_fkey`;
      out.push(
        `ALTER TABLE ${quote(entity.name)} ADD CONSTRAINT ${quote(name)} ` +
          `FOREIGN KEY (${quote(col.name)}) REFERENCES ${quote(
            col.references.entity,
          )} (${quote(col.references.column)});`,
      );
    }
  }
  return out;
}

/** Map a design column type to a concrete PostgreSQL type. */
function sqlType(type: ColumnType): string {
  switch (String(type).toLowerCase()) {
    case 'uuid':
      return 'UUID';
    case 'string':
      return 'VARCHAR(255)';
    case 'text':
      return 'TEXT';
    case 'integer':
    case 'int':
      return 'INTEGER';
    case 'bigint':
      return 'BIGINT';
    case 'decimal':
    case 'number':
    case 'float':
      return 'DECIMAL';
    case 'boolean':
    case 'bool':
      return 'BOOLEAN';
    case 'timestamp':
      return 'TIMESTAMPTZ';
    case 'date':
      return 'DATE';
    case 'json':
      return 'JSONB';
    case 'enum':
      // Enums would need a CREATE TYPE; a constrained VARCHAR keeps the script
      // self-contained and runnable.
      return 'VARCHAR(50)';
    default: {
      // Pass through anything that already looks like a SQL type (e.g.
      // "varchar(100)"); otherwise fall back to TEXT so the script stays valid.
      const raw = String(type).trim();
      return /^[a-z][a-z0-9 ()',]*$/i.test(raw) ? raw.toUpperCase() : 'TEXT';
    }
  }
}

/** Quote a SQL identifier and neutralize embedded quotes. */
function quote(id: string): string {
  return `"${String(id).replace(/"/g, '""')}"`;
}
